/**
 * PDF Renderer — converts HTML to PDF using Playwright (already installed).
 *
 * No new dependencies needed. Uses the same Chromium binary as E2E tests.
 *
 * See: Completion Plan R-03
 */

import { chromium } from 'playwright';

/**
 * Render HTML string to PDF buffer using Playwright's Chromium.
 *
 * @param html - Complete HTML document string (including <html>, <head>, <style>)
 * @returns PDF as Buffer
 */
export async function renderPdf(html: string): Promise<Buffer> {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });

    const pdf = await page.pdf({
      format: 'A4',
      margin: { top: '20mm', bottom: '25mm', left: '15mm', right: '15mm' },
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 8px; color: #999; width: 100%; padding: 0 15mm; display: flex; justify-content: space-between;">
          <span>Salesforce CPQ Assessment Report</span>
          <span>Confidential</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 8px; color: #999; width: 100%; padding: 0 15mm; display: flex; justify-content: space-between;">
          <span>Generated by RevBrain CPQ Assessment Tool</span>
          <span>Page <span class="pageNumber"></span></span>
        </div>
      `,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
