/**
 * Mock Assessment Findings — curated sample from real staging extraction.
 *
 * Provides representative data for each domain so the assessment
 * page renders with realistic content in mock mode.
 *
 * Source: 81 findings across 11 domains, sampled from the Q1
 * staging extraction (4301 total findings).
 */
import type { AssessmentFindingEntity } from '@revbrain/contract';
import { MOCK_IDS } from './constants.ts';

export const SEED_ASSESSMENT_FINDINGS: readonly AssessmentFindingEntity[] = [
  {
    id: '00000000-0000-4000-f000-000000000001',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'OrgFingerprint',
    artifactName: 'Salesforce Demo',
    artifactId: '00D3x000001AjYCEA0',
    findingKey: 'discovery:OrgFingerprint:00D3x000001AjYCEA0:default',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'record-id',
        value: '00D3x000001AjYCEA0',
        label: 'Organization',
        referencedObjects: ['Organization'],
      },
    ],
    notes: 'Enterprise Edition, CPQ 232.2.0, production',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000002',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Products',
    artifactId: null,
    findingKey: 'discovery:count_Product2:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 179,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000003',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Quotes (all)',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__Quote__c:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 23,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000004',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Quotes (90d)',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__Quote__c_90d:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 0,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000005',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Quote Lines (all)',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__QuoteLine__c:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 73,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000006',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Price Rules',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__PriceRule__c:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 28,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000007',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Product Rules',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__ProductRule__c:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 38,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000008',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'catalog',
    collectorName: 'discovery',
    artifactType: 'DataCount',
    artifactName: 'Product Options',
    artifactId: null,
    findingKey: 'discovery:count_SBQQ__ProductOption__c:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Will use REST API',
    countValue: 475,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000009',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'discovery',
    artifactType: 'UserAdoption',
    artifactName: 'CPQ User Adoption',
    artifactId: null,
    findingKey: 'discovery:user_adoption:global',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '345', label: 'CPQ Licenses' },
      { type: 'count', value: '0', label: 'Active Creators (90d)' },
      { type: 'count', value: '8', label: 'Profiles with CPQ' },
    ],
    notes: 'Licenses: 345, Active creators (90d): 0, Profiles: 8, Adoption: 0%',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000010',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSetting',
    artifactName: 'SBQQ__FieldMetadata__c',
    artifactId: null,
    findingKey: 'settings:CPQSetting:SBQQ__FieldMetadata__c',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Revenue Settings',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [],
    notes:
      "12 records (org-level + overrides). Extra metadata about the field that's not accessible via the API.",
    countValue: 12,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000011',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSettingValue',
    artifactName: 'Multi-Currency',
    artifactId: null,
    findingKey: 'settings:CPQSettingValue:Multi-Currency',
    sourceType: 'inferred',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      { type: 'field-ref', value: 'CurrencyIsoCode', label: 'Enabled (AUD, GBP, EUR, NZD, USD)' },
    ],
    notes: 'Multi-Currency: Enabled (AUD, GBP, EUR, NZD, USD)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000012',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSettingValue',
    artifactName: 'Quote Line Editor',
    artifactId: null,
    findingKey: 'settings:CPQSettingValue:Quote Line Editor',
    sourceType: 'inferred',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: 'direct',
    evidenceRefs: [{ type: 'field-ref', value: 'SBQQ__Quote__c.QLE', label: 'Enabled' }],
    notes: 'Quote Line Editor: Enabled (QLE fields detected on Quote object)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000013',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSettingValue',
    artifactName: 'Contracted Pricing',
    artifactId: null,
    findingKey: 'settings:CPQSettingValue:Contracted Pricing',
    sourceType: 'inferred',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'SBQQ__ContractedPrice__c', label: 'Enabled' }],
    notes: 'Contracted Pricing: Enabled (ContractedPrice object exists)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000014',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSettingValue',
    artifactName: 'Subscription Proration',
    artifactId: null,
    findingKey: 'settings:CPQSettingValue:Subscription Proration',
    sourceType: 'inferred',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'field-ref', value: 'SBQQ__ContractingMethod__c', label: 'By Subscription End Date' },
    ],
    notes: 'Subscription: Enabled (Contracting: By Subscription End Date)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000015',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'CPQSettingValue',
    artifactName: 'Package: Salesforce Billing',
    artifactId: null,
    findingKey: 'settings:CPQSettingValue:Package: Salesforce Billing',
    sourceType: 'inferred',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [{ type: 'field-ref', value: 'blng', label: 'v232.3.0' }],
    notes: 'Salesforce Billing (blng) v232.3.0',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000016',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings',
    collectorName: 'settings',
    artifactType: 'InstalledPackage',
    artifactName: 'Salesforce Billing',
    artifactId: null,
    findingKey: 'settings:InstalledPackage:Salesforce Billing',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'field-ref', label: 'Namespace', value: 'blng' },
      { type: 'field-ref', label: 'Version', value: '232.3.0' },
    ],
    notes: 'Salesforce Billing (blng) v232.3.0',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000017',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'discovery',
    artifactType: 'FieldCompleteness',
    artifactName: 'SBQQ__Quote__c',
    artifactId: null,
    findingKey: 'discovery:FieldCompleteness:SBQQ__Quote__c',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '48', label: 'Fields >50% populated' },
      { type: 'count', value: '26', label: 'Fields <5% populated' },
    ],
    notes: '48 of 78 fields populated above 50% threshold',
    countValue: 78,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000018',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'discovery',
    artifactType: 'FieldCompleteness',
    artifactName: 'SBQQ__QuoteLine__c',
    artifactId: null,
    findingKey: 'discovery:FieldCompleteness:SBQQ__QuoteLine__c',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '69', label: 'Fields >50% populated' },
      { type: 'count', value: '45', label: 'Fields <5% populated' },
    ],
    notes: '69 of 135 fields populated above 50% threshold',
    countValue: 135,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000019',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'discovery',
    artifactType: 'FieldCompleteness',
    artifactName: 'Product2',
    artifactId: null,
    findingKey: 'discovery:FieldCompleteness:Product2',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '69', label: 'Fields >50% populated' },
      { type: 'count', value: '44', label: 'Fields <5% populated' },
    ],
    notes: '69 of 130 fields populated above 50% threshold',
    countValue: 130,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000020',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'discovery',
    artifactType: 'FieldCompleteness',
    artifactName: 'PricebookEntry',
    artifactId: null,
    findingKey: 'discovery:FieldCompleteness:PricebookEntry',
    sourceType: 'object',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '17', label: 'Fields >50% populated' },
      { type: 'count', value: '1', label: 'Fields <5% populated' },
    ],
    notes: '17 of 18 fields populated above 50% threshold',
    countValue: 18,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000021',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'usage',
    artifactType: 'UserBehavior',
    artifactName: 'System Administrator',
    artifactId: null,
    findingKey: 'usage:UserBehavior:System Administrator',
    sourceType: 'bulk-usage',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '1', label: 'Users' },
      { type: 'count', value: '100', label: '% of quotes' },
      { type: 'count', value: '52', label: 'Conversion %' },
    ],
    notes: '1 users, 23 quotes (100%), avg $10,006, 52% conversion',
    countValue: 1,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000022',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'usage',
    artifactType: 'DiscountDistribution',
    artifactName: 'Discount Distribution (90-day)',
    artifactId: null,
    findingKey: 'usage:DiscountDistribution:Discount Distribution (90-day)',
    sourceType: 'bulk-usage',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '1', label: '0-5%' },
      { type: 'count', value: '4', label: '6-10%' },
      { type: 'count', value: '2', label: '11-15%' },
      { type: 'count', value: '0', label: '16-20%' },
      { type: 'count', value: '4', label: '>20%' },
    ],
    notes: 'Avg discount: 29%. 0-5%: 1, 6-10%: 4, 11-15%: 2, 16-20%: 0, >20%: 4',
    countValue: 11,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000023',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'usage',
    artifactType: 'PriceOverrideAnalysis',
    artifactName: 'Manual Price Overrides',
    artifactId: null,
    findingKey: 'usage:PriceOverrideAnalysis:Manual Price Overrides',
    sourceType: 'bulk-usage',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '0', label: 'Override count' },
      { type: 'count', value: '0', label: 'Override rate %' },
      { type: 'count', value: '0', label: 'Revenue impact $' },
    ],
    notes: '0 lines (0%) with manual overrides. Revenue impact: $0',
    countValue: 0,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000024',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage',
    collectorName: 'usage',
    artifactType: 'TopQuotedProduct',
    artifactName: '2-Yard Dumpster',
    artifactId: '01t3x00000AXxLcAAL',
    findingKey: 'usage:TopQuotedProduct:01t3x00000AXxLcAAL:top_product',
    sourceType: 'bulk-usage',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'field-ref', value: 'Product2.ProductCode', label: 'WW-DMP-2YD' },
      { type: 'field-ref', value: 'Product2.Family', label: 'Commercial' },
    ],
    notes: 'Category: Commercial. Quoted on 30.4% of quotes (7 / 23).',
    countValue: 7,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000025',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Lookup Approval Threshold 1',
    artifactId: 'a0V3x00000T0yciEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0yciEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'true', label: 'Active' }],
    notes:
      'Eval: On Initialization;Before Calculate;On Calculate;After Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000026',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Lookup Approval Threshold 2',
    artifactId: 'a0V3x00000T0ycjEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0ycjEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'true', label: 'Active' }],
    notes:
      'Eval: On Initialization;Before Calculate;On Calculate;After Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000027',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Lookup Approval Threshold 3',
    artifactId: 'a0V3x00000T0yckEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0yckEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'true', label: 'Active' }],
    notes:
      'Eval: On Initialization;Before Calculate;On Calculate;After Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000028',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Set SB Pricing in Config',
    artifactId: 'a0V3x00000T0yclEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0yclEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'true', label: 'Active' }],
    notes: 'Eval: null, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000029',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Set SB Pricing in QLE',
    artifactId: 'a0V3x00000T0ycmEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0ycmEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'true', label: 'Active' }],
    notes: 'Eval: On Initialization;On Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000030',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Copy Of Inventory',
    artifactId: 'a0V3x00000T0ycnEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0ycnEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'optional',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'false', label: 'Active' }],
    notes: 'Inactive — Eval: On Initialization;On Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000031',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Inventory - Config',
    artifactId: 'a0V3x00000T0ycoEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0ycoEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'optional',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'false', label: 'Active' }],
    notes: 'Inactive — Eval: On Initialization;On Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000032',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'pricing',
    collectorName: 'pricing',
    artifactType: 'SBQQ__PriceRule__c',
    artifactName: 'Inventory Price - Config',
    artifactId: 'a0V3x00000T0ycpEAB',
    findingKey: 'pricing:SBQQ__PriceRule__c:a0V3x00000T0ycpEAB:price_rule',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'optional',
    rcaTargetConcept: 'PricingProcedure',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [{ type: 'field-ref', value: 'false', label: 'Active' }],
    notes: 'Inactive — Eval: On Initialization;On Calculate, Scope: undefined',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000033',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'CPQB_QuickSelectCTRL',
    artifactId: '01p3x000002MeS0AAK',
    findingKey: 'dependencies:ApexClass:01p3x000002MeS0AAK:apex_cpq_related',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Apex or Flow',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      {
        type: 'code-snippet',
        value:
          'public with sharing class CPQB_QuickSelectCTRL {\n    public class SourceModel {\n        @Auraenabled public String Name;\n        @Auraenabled public String Family;\n        @Auraenabled public String Code;\n        @Auraenabled public String Id;\n    }\n\n    @AuraEnabled\n    public static List<SourceModel> initializeProducts() {\n        //return [SELECT Id, Name FROM Product2];\n        String userCurrency = UserInfo.getDefaultCurrency();\n        List<PricebookEntry> pbes = getPricebookEntries(userCu',
        label: 'Apex: CPQB_QuickSelectCTRL',
        referencedObjects: [
          'SBQQ__Quote__c',
          'SBQQ__QuoteLine__c',
          'SBQQ__QuoteLineGroup__c',
          'Product2',
          'Opportunity',
          'Order',
          'Account',
        ],
        referencedFields: [
          'SBQQ__Quote__c',
          'SBQQ__Quote__c',
          'SBQQ__Quote__c',
          'SBQQ__Quote__c',
          'SBQQ__Type__c',
          'SBQQ__Status__c',
          'SBQQ__Primary__c',
          'SBQQ__SubscriptionTerm__c',
          'SBQQ__StartDate__c',
          'SBQQ__ExpirationDate__c',
          'SBQQ__PricebookId__c',
          'SBQQ__Opportunity2__c',
          'SBQQ__Account__c',
          'SBQQ__Product__c',
          'SBQQ__NetTotal__c',
          'SBQQ__Quantity__c',
          'SBQQ__Quote__c',
          'SBQQ__QuoteLine__c',
          'SBQQ__QuoteLineGroup__c',
          'SBQQ__ProductOption__c',
        ],
        truncated: true,
        originalBytes: 16093,
      },
      { type: 'field-ref', value: 'dynamicDispatchPattern', label: 'Database.query' },
    ],
    notes: 'CPQ-related Apex. Concerns: pricing, quote-sync',
    countValue: 403,
    textValue:
      'public with sharing class CPQB_QuickSelectCTRL {\n    public class SourceModel {\n        @Auraenabled public String Name;\n        @Auraenabled public String Family;\n        @Auraenabled public String C',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000034',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'InvoiceViewTests',
    artifactId: '01p3x000002MehdAAC',
    findingKey: 'dependencies:ApexClass:01p3x000002MehdAAC:apex_test_class',
    sourceType: 'tooling',
    riskLevel: 'low',
    complexityLevel: 'low',
    migrationRelevance: 'optional',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'code-snippet',
        value: '@isTest in InvoiceViewTests',
        label: 'Apex test: InvoiceViewTests',
      },
    ],
    notes:
      'Apex test class — excluded from migration metrics. Tests must be re-run on the target platform but do not migrate as code.',
    countValue: 127,
    textValue:
      "/**\n * Created by scheck on 8/6/18.\n */\n\n@IsTest\nprivate class InvoiceViewTests {\n\n    @TestSetup static void setup(){\n        Account testAccount = new Account(\n                Name='Universal Testin",
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000035',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'QuickQuoteTests',
    artifactId: '01p3x000002MeheAAC',
    findingKey: 'dependencies:ApexClass:01p3x000002MeheAAC:apex_test_class',
    sourceType: 'tooling',
    riskLevel: 'low',
    complexityLevel: 'low',
    migrationRelevance: 'optional',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'code-snippet',
        value: '@isTest in QuickQuoteTests',
        label: 'Apex test: QuickQuoteTests',
      },
    ],
    notes:
      'Apex test class — excluded from migration metrics. Tests must be re-run on the target platform but do not migrate as code.',
    countValue: 17,
    textValue:
      "/**\n * Created by scheck on 8/6/18.\n */\n\n@IsTest\nprivate class QuickQuoteTests {\n\n    @IsTest(SeeAllData=true)\n    static void testCreateQuote(){\n        String startDate = '08/31/2020';\n        Integ",
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000036',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'SubscriptionViewTests',
    artifactId: '01p3x000002MehfAAC',
    findingKey: 'dependencies:ApexClass:01p3x000002MehfAAC:apex_test_class',
    sourceType: 'tooling',
    riskLevel: 'low',
    complexityLevel: 'low',
    migrationRelevance: 'optional',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'code-snippet',
        value: '@isTest in SubscriptionViewTests',
        label: 'Apex test: SubscriptionViewTests',
      },
    ],
    notes:
      'Apex test class — excluded from migration metrics. Tests must be re-run on the target platform but do not migrate as code.',
    countValue: 163,
    textValue:
      "/**\n * Created by scheck on 8/6/18.\n */\n\n@IsTest\nprivate class SubscriptionViewTests {\n\n    @TestSetup static void setup(){\n        Account testAccount = new Account(\n                Name='Universal T",
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000037',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'CPQB_UploadUsageCTRL',
    artifactId: '01p3x000002MeS5AAK',
    findingKey: 'dependencies:ApexClass:01p3x000002MeS5AAK:apex_cpq_related',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Apex or Flow',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      {
        type: 'code-snippet',
        value:
          "public with sharing class CPQB_UploadUsageCTRL {\n    \n    @AuraEnabled\n    public static List<blng__Usage__c> onProcessBatch(String base64){\n        System.debug(base64);\n        String decodedCSV = EncodingUtil.base64Decode(base64.split(',')[1]).toString();\n\n        // this will split into a few lines on the system debug! \n        System.debug(decodedCSV);\n        List<blng__Usage__c> usages = csvToUsage(decodedCSV);\n        return usages;\n    }\n\n    public static List<blng__Usage__c> csvToUsag",
        label: 'Apex: CPQB_UploadUsageCTRL',
        referencedObjects: [],
        referencedFields: [],
        truncated: true,
        originalBytes: 2089,
      },
    ],
    notes: 'CPQ-related Apex. Concerns: general',
    countValue: 49,
    textValue:
      'public with sharing class CPQB_UploadUsageCTRL {\n    \n    @AuraEnabled\n    public static List<blng__Usage__c> onProcessBatch(String base64){\n        System.debug(base64);\n        String decodedCSV = E',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000038',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'AccountUtilitiesController',
    artifactId: '01p3x000002MeSDAA0',
    findingKey: 'dependencies:ApexClass:01p3x000002MeSDAA0:apex_cpq_related',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Apex or Flow',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      {
        type: 'code-snippet',
        value:
          'public without sharing class AccountUtilitiesController {\n\n    public Id AccountId { get; set; }\n    private ApexPages.StandardController Controller;\n    private Id[] QuotesToDelete;\n\n    //CONSTRUCTOR for VF Pages\n    public AccountUtilitiesController(ApexPages.StandardController stdController) {\n        this.AccountId = stdController.getId();\n        this.Controller = stdController;\n    }\n\n    public PageReference resetAccount() {\n        this.disableBillingTriggers();\n        this.deleteDiscS',
        label: 'Apex: AccountUtilitiesController',
        referencedObjects: [
          'SBQQ__Quote__c',
          'Opportunity',
          'Order',
          'OrderItem',
          'Contract',
          'Account',
          'blng__Invoice__c',
          'blng__CreditNote__c',
        ],
        referencedFields: [
          'SBQQ__DiscountSchedule__c',
          'SBQQ__DiscountSchedule__c',
          'SBQQ__Account__c',
          'SBQQ__ProcessInputValue__c',
          'SBQQ__ProcessInputValue__c',
          'SBQQ__QuoteId__c',
          'SBQQ__Contracted__c',
          'SBQQ__Contracted__c',
          'SBQQ__QuoteDocument__c',
          'SBQQ__QuoteDocument__c',
          'SBQQ__Opportunity__c',
          'SBQQ__Subscription__c',
          'SBQQ__Subscription__c',
          'SBQQ__RenewalOpportunity__c',
          'SBQQ__RenewalOpportunity__c',
          'SBQQ__Quote__c',
          'SBQQ__Quote__c',
          'SBQQ__Quote__c',
        ],
        truncated: true,
        originalBytes: 13777,
      },
    ],
    notes: 'CPQ-related Apex. Concerns: pricing, quote-sync',
    countValue: 369,
    textValue:
      'public without sharing class AccountUtilitiesController {\n\n    public Id AccountId { get; set; }\n    private ApexPages.StandardController Controller;\n    private Id[] QuotesToDelete;\n\n    //CONSTRUCTO',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000039',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'ProductUtility',
    artifactId: '01p3x000002MeSFAA0',
    findingKey: 'dependencies:ApexClass:01p3x000002MeSFAA0:apex_cpq_related',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Apex or Flow',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      {
        type: 'code-snippet',
        value:
          "/**\n * QTC CDEMO Template Org Product Utility \n * @author Matthew Seeger\n *\n * Modified by sean crowe November 21 2017\n *\n */\npublic class ProductUtility {\n    public static void BeforeTriggerProcessor(List<Product2> allProds) {\n\n        Id DefaultBilling = [SELECT Id FROM blng__BillingRule__c WHERE Name = 'Invoice w/ Special Treatment' LIMIT 1].Id;\n        Id DefaultRevRec = [SELECT Id FROM blng__RevenueRecognitionRule__c WHERE Name = '100% Ratable (Monthly)' LIMIT 1].Id;\n        Id DefaultTax ",
        label: 'Apex: ProductUtility',
        referencedObjects: ['Product2'],
        referencedFields: [
          'SBQQ__ChargeType__c',
          'SBQQ__ChargeType__c',
          'SBQQ__ChargeType__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Product__c',
          'SBQQ__UnitCost__c',
          'SBQQ__Cost__c',
          'SBQQ__Product__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
          'SBQQ__Product__c',
          'SBQQ__Cost__c',
          'SBQQ__Cost__c',
        ],
        truncated: true,
        originalBytes: 11552,
      },
    ],
    notes: 'CPQ-related Apex. Concerns: approvals',
    countValue: 244,
    textValue:
      '/**\n * QTC CDEMO Template Org Product Utility \n * @author Matthew Seeger\n *\n * Modified by sean crowe November 21 2017\n *\n */\npublic class ProductUtility {\n    public static void BeforeTriggerProcesso',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000040',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'dependency',
    collectorName: 'dependencies',
    artifactType: 'ApexClass',
    artifactName: 'Kodiak_AccountBillingSetupController',
    artifactId: '01p3x000002MeS6AAK',
    findingKey: 'dependencies:ApexClass:01p3x000002MeS6AAK:apex_cpq_related',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Apex or Flow',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [
      {
        type: 'code-snippet',
        value:
          'public with sharing class Kodiak_AccountBillingSetupController { \n\n    @AuraEnabled\n    public static Boolean showAlert(Id recordId){\n        Account thisAccount = [SELECT \n                                    Id,\n                                    Accounting_Finance_Book__c,\n                                    Legal_Entity__c,\n                                    blng__BillToContact__c\n                                FROM Account\n                                WHERE Id = :recordId];\n        if(',
        label: 'Apex: Kodiak_AccountBillingSetupController',
        referencedObjects: ['Account'],
        referencedFields: [],
        truncated: true,
        originalBytes: 3672,
      },
    ],
    notes: 'CPQ-related Apex. Concerns: general',
    countValue: 97,
    textValue:
      'public with sharing class Kodiak_AccountBillingSetupController { \n\n    @AuraEnabled\n    public static Boolean showAlert(Id recordId){\n        Account thisAccount = [SELECT \n                           ',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000041',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.Product_Picture__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.Product_Picture__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value:
          'IF(CONTAINS(Product_Picture_ID_URL__c,"."), \r\n\r\nIF(ISBLANK(Product_Picture_ID_URL__c), IMAGE("https://i.imgur.com/dLYhAHd.jpg", "", 100, 100),IMAGE((Product_Picture_ID_URL__c), "", Product_Image_Height__c, Product_Image_Width__c)), \r\n\r\n(IF(ISBLANK(Product_Picture_ID_URL__c), IMAGE("https://i.imgur.com/dLYhAHd.jpg", "", 100, 100),IMAGE("/servlet/servlet.ImageServer?id=" + Product_Picture_ID_URL__c + "&oid=" + $Organization.Id , "", Product_Image_Height__c, Product_Image_Width__c))))',
        label: 'Product_Picture__c',
        referencedObjects: ['Product2'],
        referencedFields: ['Product_Picture__c'],
      },
    ],
    notes: 'Formula field on Product2: Product Picture (string)',
    countValue: null,
    textValue:
      'IF(CONTAINS(Product_Picture_ID_URL__c,"."), \r\n\r\nIF(ISBLANK(Product_Picture_ID_URL__c), IMAGE("https://i.imgur.com/dLYhAHd.jpg", "", 100, 100),IMAGE((Product_Picture_ID_URL__c), "", Product_Image_Heigh',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000042',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.Is_Evergreen__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.Is_Evergreen__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value:
          'if(ispickval(SBQQ__SubscriptionType__c, "Renewable/Evergreen") || ispickval(SBQQ__SubscriptionType__c, "Evergreen"), True, False)',
        label: 'Is_Evergreen__c',
        referencedObjects: ['Product2'],
        referencedFields: ['Is_Evergreen__c'],
      },
    ],
    notes: 'Formula field on Product2: Evergreen (boolean)',
    countValue: null,
    textValue:
      'if(ispickval(SBQQ__SubscriptionType__c, "Renewable/Evergreen") || ispickval(SBQQ__SubscriptionType__c, "Evergreen"), True, False)',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000043',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.Help__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.Help__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value:
          'HYPERLINK( Help_Link__c , IMAGE("/servlet/servlet.ImageServer?id=0153x0000056nNX&oid=00D3x000001AjYC&lastMod=1589228835000","Help",40,40) , "_blank")',
        label: 'Help__c',
        referencedObjects: ['Product2'],
        referencedFields: ['Help__c'],
      },
    ],
    notes: 'Formula field on Product2: Help (string)',
    countValue: null,
    textValue:
      'HYPERLINK( Help_Link__c , IMAGE("/servlet/servlet.ImageServer?id=0153x0000056nNX&oid=00D3x000001AjYC&lastMod=1589228835000","Help",40,40) , "_blank")',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000044',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.Base_SSP__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.Base_SSP__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value: 'Standalone_Selling_Price__r.Base_SSP__c',
        label: 'Base_SSP__c',
        referencedObjects: ['Product2'],
        referencedFields: ['Base_SSP__c'],
      },
    ],
    notes: 'Formula field on Product2: Base SSP (currency)',
    countValue: null,
    textValue: 'Standalone_Selling_Price__r.Base_SSP__c',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000045',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.SSP_High_Value__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.SSP_High_Value__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value: 'Standalone_Selling_Price__r.SSP_High_Value__c',
        label: 'SSP_High_Value__c',
        referencedObjects: ['Product2'],
        referencedFields: ['SSP_High_Value__c'],
      },
    ],
    notes: 'Formula field on Product2: SSP High Value (currency)',
    countValue: null,
    textValue: 'Standalone_Selling_Price__r.SSP_High_Value__c',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000046',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'Product2.SSP_Low_Value__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:Product2.SSP_Low_Value__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value: 'Standalone_Selling_Price__r.SSP_Low_Value__c',
        label: 'SSP_Low_Value__c',
        referencedObjects: ['Product2'],
        referencedFields: ['SSP_Low_Value__c'],
      },
    ],
    notes: 'Formula field on Product2: SSP Low Value (currency)',
    countValue: null,
    textValue: 'Standalone_Selling_Price__r.SSP_Low_Value__c',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000047',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'SBQQ__Quote__c.Print_Names__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:SBQQ__Quote__c.Print_Names__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value:
          'ISPICKVAL( Product_Detail__c , "Names") || ISPICKVAL( Product_Detail__c , "Both") || ISPICKVAL(Product_Detail__c, "")',
        label: 'Print_Names__c',
        referencedObjects: ['SBQQ__Quote__c'],
        referencedFields: ['Print_Names__c'],
      },
    ],
    notes: 'Formula field on SBQQ__Quote__c: Print Names (boolean)',
    countValue: null,
    textValue:
      'ISPICKVAL( Product_Detail__c , "Names") || ISPICKVAL( Product_Detail__c , "Both") || ISPICKVAL(Product_Detail__c, "")',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000048',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'customization',
    collectorName: 'customizations',
    artifactType: 'FormulaField',
    artifactName: 'SBQQ__Quote__c.Print_Descriptions__c',
    artifactId: null,
    findingKey: 'customizations:FormulaField:SBQQ__Quote__c.Print_Descriptions__c',
    sourceType: 'metadata',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      {
        type: 'formula',
        value:
          'ISPICKVAL( Product_Detail__c , "Descriptions") || ISPICKVAL( Product_Detail__c , "Both")',
        label: 'Print_Descriptions__c',
        referencedObjects: ['SBQQ__Quote__c'],
        referencedFields: ['Print_Descriptions__c'],
      },
    ],
    notes: 'Formula field on SBQQ__Quote__c: Print Descriptions (boolean)',
    countValue: null,
    textValue:
      'ISPICKVAL( Product_Detail__c , "Descriptions") || ISPICKVAL( Product_Detail__c , "Both")',
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000049',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle',
    collectorName: 'order-lifecycle',
    artifactType: 'OrderLifecycleOverview',
    artifactName: 'Order/Contract/Asset Lifecycle',
    artifactId: null,
    findingKey: 'order-lifecycle:lifecycle_overview:global',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Orders: 558, OrderItems: 5736, Contracts: 314 (314 active), Assets w/ subs: N/A',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000050',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Proposal With Usage',
    artifactId: 'a0j3x000011QEvKAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvKAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Proposal With Usage. Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000051',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Quote',
    artifactId: 'a0j3x000011QEvLAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvLAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Quote. Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000052',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Contract',
    artifactId: 'a0j3x000011QEvMAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvMAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Contract. Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000053',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Proposal',
    artifactId: 'a0j3x000011QEvNAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvNAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Proposal (DEFAULT). Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000054',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Proposal w/ Subs and One-Time Prods',
    artifactId: 'a0j3x000011QEvOAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvOAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Proposal w/ Subs and One-Time Prods. Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000055',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'QuoteTemplate',
    artifactName: 'Proposal Multilanguage',
    artifactId: 'a0j3x000011QEvPAAW',
    findingKey: 'templates:QuoteTemplate:a0j3x000011QEvPAAW:quote_template',
    sourceType: 'object',
    riskLevel: null,
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Template: Proposal Multilanguage (DEFAULT). Font: Helvetica, Size: 9',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000056',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'Document',
    artifactName: 'SteelBrick Watermark',
    artifactId: '0153x0000056nNrAAI',
    findingKey: 'templates:Document:0153x0000056nNrAAI:template_document_ref',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Salesforce Files',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [],
    notes:
      'Referenced document: SteelBrick Watermark (image/png, 81545 bytes). Must migrate to Salesforce Files.',
    countValue: 81545,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000057',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'templates',
    collectorName: 'templates',
    artifactType: 'TemplateSection',
    artifactName: 'conditional_sections_summary',
    artifactId: null,
    findingKey: 'templates:TemplateSection:conditional_sections_summary',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'high',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Document Generation conditional logic',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes:
      '21 template sections use conditional print fields — logic must be recreated in RCA document generation',
    countValue: 21,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000058',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Amend Assets',
    artifactId: 'a073x000015EB96AAG',
    findingKey: 'approvals:CustomAction:a073x000015EB96AAG:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Custom Action: Amend Assets — Type: Button, Location: Account Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000059',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Renew Assets',
    artifactId: 'a073x000015EB97AAG',
    findingKey: 'approvals:CustomAction:a073x000015EB97AAG:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Custom Action: Renew Assets — Type: Button, Location: Account Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000060',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Amend',
    artifactId: 'a073x000015EB98AAG',
    findingKey: 'approvals:CustomAction:a073x000015EB98AAG:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Custom Action: Amend — Type: Button, Location: Contract Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000061',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Renew Contracts',
    artifactId: 'a073x000015EB99AAG',
    findingKey: 'approvals:CustomAction:a073x000015EB99AAG:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Custom Action: Renew Contracts — Type: Button, Location: Contract Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000062',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Include Document',
    artifactId: 'a073x000015EB9AAAW',
    findingKey: 'approvals:CustomAction:a073x000015EB9AAAW:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes:
      'Custom Action: Include Document — Type: Button, Location: Opportunity Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000063',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Amend Contract',
    artifactId: 'a073x000015EB9BAAW',
    findingKey: 'approvals:CustomAction:a073x000015EB9BAAW:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes:
      'Custom Action: Amend Contract — Type: Button, Location: Opportunity Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000064',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Create Order',
    artifactId: 'a073x000015EB9CAAW',
    findingKey: 'approvals:CustomAction:a073x000015EB9CAAW:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes: 'Custom Action: Create Order — Type: Button, Location: Opportunity Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000065',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'approvals',
    collectorName: 'approvals',
    artifactType: 'CustomAction',
    artifactName: 'Edit Order Products',
    artifactId: 'a073x000015EB9DAAW',
    findingKey: 'approvals:CustomAction:a073x000015EB9DAAW:custom_action',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Flow-based approval orchestration',
    rcaMappingComplexity: 'redesign',
    evidenceRefs: [],
    notes:
      'Custom Action: Edit Order Products — Type: Button, Location: Order Panel, Target: unset',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000066',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'NamedCredential',
    artifactName: 'Salesforce',
    artifactId: '0XA3x0000004COnGAM',
    findingKey: 'integrations:NamedCredential:0XA3x0000004COnGAM:named_credential',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Named Credentials (reusable)',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Named Credential: Salesforce → https://salesforce.com (NamedUser)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000067',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'OpportunityContactRole',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:OpportunityContactRole',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: OpportunityContactRole (Opportunity Contact Role)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000068',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'Case',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:Case',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: Case (Case)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000069',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'EmailMessage',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:EmailMessage',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: EmailMessage (Email Message)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000070',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'Quote',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:Quote',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: Quote (Quote)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000071',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'EntityMilestone',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:EntityMilestone',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: EntityMilestone (Object Milestone)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000072',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'WorkBadge',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:WorkBadge',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: WorkBadge (Badge Received)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000073',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'integration',
    collectorName: 'integrations',
    artifactType: 'PlatformEvent',
    artifactName: 'ContactPointPhone',
    artifactId: null,
    findingKey: 'integrations:PlatformEvent:ContactPointPhone',
    sourceType: 'tooling',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: 'Platform Event',
    rcaMappingComplexity: 'direct',
    evidenceRefs: [],
    notes: 'Platform Event: ContactPointPhone (Contact Point Phone)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000074',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'localization',
    artifactType: 'LocalizationSummary',
    artifactName: 'cpq_localization_overview',
    artifactId: null,
    findingKey: 'localization:LocalizationSummary:cpq_localization_overview',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: 'medium',
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Translation Workbench',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [],
    notes:
      '269 localization records across 4 languages (es, en_US, it, de). 3 templates, 22 products translated.',
    countValue: 269,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000075',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'localization',
    artifactType: 'LanguageTranslation',
    artifactName: 'language_es',
    artifactId: null,
    findingKey: 'localization:LanguageTranslation:language_es',
    sourceType: 'object',
    riskLevel: 'medium',
    complexityLevel: null,
    migrationRelevance: 'must-migrate',
    rcaTargetConcept: 'Translation Workbench',
    rcaMappingComplexity: 'transform',
    evidenceRefs: [],
    notes: '211 localization records for language: es',
    countValue: 211,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000076',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'GeneralCPQB',
    artifactId: '1013x0000027RuMAAU',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027RuMAAU:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: GeneralCPQB (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000077',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'B2B_FP_Invalid_Boolean_Field_Value',
    artifactId: '1013x0000027QKbAAM',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027QKbAAM:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: B2B FP Invalid Boolean Field Value (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000078',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'B2B_FP_Invalid_Compare_Type',
    artifactId: '1013x0000027QKcAAM',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027QKcAAM:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: B2B FP Invalid Compare Type (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000079',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'B2B_FP_Component_configuration_error',
    artifactId: '1013x0000027QKdAAM',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027QKdAAM:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: B2B FP Component configuration error (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000080',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'B2B_FP_Field_is_not_accessible',
    artifactId: '1013x0000027QKeAAM',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027QKeAAM:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: B2B FP Field is not accessible (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000081',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'localization',
    collectorName: 'tier2-inventories',
    artifactType: 'CustomLabel',
    artifactName: 'B2B_FP_No_Products',
    artifactId: '1013x0000027QKfAAM',
    findingKey: 'tier2-inventories:CustomLabel:1013x0000027QKfAAM:custom_label',
    sourceType: 'tooling',
    riskLevel: 'info',
    complexityLevel: null,
    migrationRelevance: 'should-migrate',
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'Custom label: B2B FP No Products (en_US)',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // ============================================================================
  // V11 — Transactional Object Metadata (Section 6.8 master table)
  // ============================================================================
  ...(
    [
      'Opportunity',
      'OpportunityLineItem',
      'SBQQ__Quote__c',
      'SBQQ__QuoteLine__c',
      'Order',
      'OrderItem',
      'Contract',
      'SBQQ__Subscription__c',
    ] as const
  ).map((apiName, i) => {
    const labels: Record<string, string> = {
      Opportunity: 'Opportunity',
      OpportunityLineItem: 'Opportunity Product',
      SBQQ__Quote__c: 'Quote',
      SBQQ__QuoteLine__c: 'Quote Line',
      Order: 'Order',
      OrderItem: 'Order Product',
      Contract: 'Contract',
      SBQQ__Subscription__c: 'Subscription',
    };
    const mockData: Record<
      string,
      {
        pl: number;
        btn: number;
        fs: number;
        rt: number;
        vr: number;
        cf: number;
        mgd: number;
        org: number;
      }
    > = {
      Opportunity: { pl: 3, btn: 5, fs: 2, rt: 5, vr: 2, cf: 59, mgd: 14, org: 45 },
      OpportunityLineItem: { pl: 2, btn: 3, fs: 1, rt: 0, vr: 1, cf: 28, mgd: 12, org: 16 },
      SBQQ__Quote__c: { pl: 4, btn: 15, fs: 3, rt: 2, vr: 4, cf: 180, mgd: 150, org: 30 },
      SBQQ__QuoteLine__c: { pl: 2, btn: 8, fs: 2, rt: 0, vr: 3, cf: 250, mgd: 220, org: 30 },
      Order: { pl: 2, btn: 4, fs: 0, rt: 3, vr: 2, cf: 35, mgd: 10, org: 25 },
      OrderItem: { pl: 1, btn: 2, fs: 0, rt: 0, vr: 1, cf: 22, mgd: 8, org: 14 },
      Contract: { pl: 3, btn: 3, fs: 1, rt: 2, vr: 2, cf: 42, mgd: 18, org: 24 },
      SBQQ__Subscription__c: { pl: 1, btn: 2, fs: 0, rt: 0, vr: 1, cf: 95, mgd: 85, org: 10 },
    };
    const d = mockData[apiName]!;
    return {
      id: `00000000-0000-4000-f000-000000000${100 + i}`,
      runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
      domain: 'transactional-objects' as const,
      collectorName: 'transactional-objects',
      artifactType: 'TransactionalObjectMeta',
      artifactName: labels[apiName]!,
      artifactId: null,
      findingKey: `transactional-objects:TransactionalObjectMeta:${apiName}:object_meta`,
      sourceType: 'object' as const,
      riskLevel: null,
      complexityLevel: null,
      migrationRelevance: null,
      rcaTargetConcept: null,
      rcaMappingComplexity: null,
      evidenceRefs: [
        { type: 'object-ref', value: apiName, label: 'API Name' },
        { type: 'count', value: String(d.fs), label: 'Field Sets' },
        { type: 'count', value: String(d.rt), label: 'Active Record Types' },
        { type: 'count', value: String(d.cf), label: 'Custom Fields Total' },
        { type: 'count', value: String(d.mgd), label: 'Custom Fields Managed' },
        { type: 'count', value: String(d.org), label: 'Custom Fields Org-Owned' },
      ],
      notes: `${d.cf} total (${d.mgd} managed / ${d.org} org-owned)`,
      countValue: null,
      textValue: null,
      createdAt: new Date('2026-04-10T12:00:00Z'),
    } satisfies AssessmentFindingEntity;
  }),

  // V11 — Transactional Object Tooling (Page Layouts, Buttons/Links, Validation Rules)
  ...(
    [
      'Opportunity',
      'OpportunityLineItem',
      'SBQQ__Quote__c',
      'SBQQ__QuoteLine__c',
      'Order',
      'OrderItem',
      'Contract',
      'SBQQ__Subscription__c',
    ] as const
  ).map((apiName, i) => {
    const labels: Record<string, string> = {
      Opportunity: 'Opportunity',
      OpportunityLineItem: 'Opportunity Product',
      SBQQ__Quote__c: 'Quote',
      SBQQ__QuoteLine__c: 'Quote Line',
      Order: 'Order',
      OrderItem: 'Order Product',
      Contract: 'Contract',
      SBQQ__Subscription__c: 'Subscription',
    };
    const mockData: Record<
      string,
      { pl: number; btn: number; wl: number; qa: number; vr: number }
    > = {
      Opportunity: { pl: 3, btn: 5, wl: 3, qa: 2, vr: 2 },
      OpportunityLineItem: { pl: 2, btn: 3, wl: 2, qa: 1, vr: 1 },
      SBQQ__Quote__c: { pl: 4, btn: 15, wl: 5, qa: 10, vr: 4 },
      SBQQ__QuoteLine__c: { pl: 2, btn: 8, wl: 4, qa: 4, vr: 3 },
      Order: { pl: 2, btn: 4, wl: 3, qa: 1, vr: 2 },
      OrderItem: { pl: 1, btn: 2, wl: 1, qa: 1, vr: 1 },
      Contract: { pl: 3, btn: 3, wl: 2, qa: 1, vr: 2 },
      SBQQ__Subscription__c: { pl: 1, btn: 2, wl: 1, qa: 1, vr: 1 },
    };
    const d = mockData[apiName]!;
    return {
      id: `00000000-0000-4000-f000-000000000${110 + i}`,
      runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
      domain: 'transactional-objects' as const,
      collectorName: 'transactional-objects',
      artifactType: 'TransactionalObjectTooling',
      artifactName: labels[apiName]!,
      artifactId: null,
      findingKey: `transactional-objects:TransactionalObjectTooling:${apiName}:object_tooling`,
      sourceType: 'tooling' as const,
      riskLevel: null,
      complexityLevel: null,
      migrationRelevance: null,
      rcaTargetConcept: null,
      rcaMappingComplexity: null,
      evidenceRefs: [
        { type: 'object-ref', value: apiName, label: 'API Name' },
        { type: 'count', value: String(d.pl), label: 'Page Layouts' },
        { type: 'count', value: String(d.btn), label: 'Buttons/Links/Actions' },
        { type: 'count', value: String(d.wl), label: 'WebLinks' },
        { type: 'count', value: String(d.qa), label: 'QuickActions' },
        { type: 'count', value: String(d.vr), label: 'Active Validation Rules' },
      ],
      notes: null,
      countValue: null,
      textValue: null,
      createdAt: new Date('2026-04-10T12:00:00Z'),
    } satisfies AssessmentFindingEntity;
  }),

  // V11 — DataCount findings for new transactional objects
  ...(
    [
      { name: 'Opportunity', label: 'Opportunities (all)', count: 1250 },
      { name: 'Opportunity_90d', label: 'Opportunities (90d)', count: 85 },
      { name: 'OpportunityLineItem', label: 'Opportunity Products (all)', count: 4800 },
      { name: 'Order', label: 'Orders (all)', count: 380 },
      { name: 'Order_90d', label: 'Orders (90d)', count: 12 },
      { name: 'OrderItem', label: 'Order Products (all)', count: 1450 },
      { name: 'Contract', label: 'Contracts (all)', count: 220 },
      { name: 'Contract_90d', label: 'Contracts (90d)', count: 8 },
      { name: 'SBQQ__Subscription__c', label: 'Subscriptions (all)', count: 890 },
      { name: 'SBQQ__QuoteLine__c_90d', label: 'Quote Lines (90d)', count: 73 },
      { name: 'SBQQ__SummaryVariable__c', label: 'Summary Variables', count: 8 },
      { name: 'SBQQ__SearchFilter__c', label: 'Search Filters', count: 3 },
      { name: 'SBQQ__QuoteProcess__c', label: 'Quote Processes (Guided Selling)', count: 2 },
      { name: 'SBQQ__ProcessInput__c', label: 'Process Inputs (Guided Selling)', count: 12 },
      { name: 'SBQQ__LookupQuery__c', label: 'Lookup Queries', count: 5 },
      { name: 'SBQQ__LookupData__c', label: 'Lookup Data', count: 15 },
    ] as const
  ).map(
    (obj, i) =>
      ({
        id: `00000000-0000-4000-f000-000000000${120 + i}`,
        runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
        domain: 'catalog' as const,
        collectorName: 'discovery',
        artifactType: 'DataCount',
        artifactName: obj.label,
        artifactId: null,
        findingKey: `discovery:count_${obj.name}:global`,
        sourceType: 'object' as const,
        riskLevel: null,
        complexityLevel: null,
        migrationRelevance: null,
        rcaTargetConcept: null,
        rcaMappingComplexity: null,
        evidenceRefs: [],
        notes: 'Will use REST API',
        countValue: obj.count,
        textValue: null,
        createdAt: new Date('2026-04-10T12:00:00Z'),
      }) satisfies AssessmentFindingEntity
  ),

  // V11 — Contract classification detail
  {
    id: '00000000-0000-4000-f000-000000000140',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle' as const,
    collectorName: 'order-lifecycle',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Contracts — Classification & Renewal',
    artifactId: null,
    findingKey: 'order-lifecycle:TransactionalObjectDetail:Contract:contract_classification',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '220', label: 'Total Contracts (evaluated population)' },
      { type: 'count', value: '85', label: 'Renewals' },
      { type: 'count', value: '45', label: 'Amendments' },
      { type: 'count', value: '90', label: 'New / Unclassified' },
      { type: 'count', value: '72', label: 'Renewal Forecast = TRUE' },
      { type: 'count', value: '58', label: 'Renewal Quoted = TRUE' },
    ],
    notes: 'Scope: all-time contracts assessed. Classification via explicit CPQ lineage fields.',
    countValue: 220,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Subscription lifecycle detail
  {
    id: '00000000-0000-4000-f000-000000000141',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle' as const,
    collectorName: 'order-lifecycle',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Subscriptions — Lifecycle Analysis',
    artifactId: null,
    findingKey:
      'order-lifecycle:TransactionalObjectDetail:SBQQ__Subscription__c:subscription_lifecycle',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '890', label: 'Total Subscriptions' },
      { type: 'count', value: '125', label: 'Amended Subscriptions' },
      { type: 'count', value: '210', label: 'Renewed Subscriptions' },
      {
        type: 'field-ref',
        value: 'SBQQ__RevisedSubscription__c',
        label: 'Renewed detection field',
      },
    ],
    notes: 'All-time counts. Amended detected via SBQQ__RevisedSubscription__c.',
    countValue: 890,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Orders detail
  {
    id: '00000000-0000-4000-f000-000000000142',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle' as const,
    collectorName: 'order-lifecycle',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Orders — Quote Split Analysis',
    artifactId: null,
    findingKey: 'order-lifecycle:TransactionalObjectDetail:Order:orders_per_quote',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '12', label: 'Orders in 90-day window' },
      { type: 'count', value: '10', label: 'Ordered Quotes (Primary=TRUE, Ordered=TRUE)' },
      { type: 'count', value: '1.2', label: 'Avg Orders per Ordered Quote' },
    ],
    notes: null,
    countValue: 12,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — OLI not contracted + billing signal
  {
    id: '00000000-0000-4000-f000-000000000143',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle' as const,
    collectorName: 'order-lifecycle',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Order Products — Contracting Pattern',
    artifactId: null,
    findingKey: 'order-lifecycle:TransactionalObjectDetail:OrderItem:oli_contracting',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [{ type: 'count', value: '3', label: 'OLIs with Ordered=FALSE (90d)' }],
    notes: null,
    countValue: 3,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000144',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'order-lifecycle' as const,
    collectorName: 'order-lifecycle',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Order Products — Billing Signal',
    artifactId: null,
    findingKey: 'order-lifecycle:TransactionalObjectDetail:OrderItem:oli_billing',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [],
    notes: 'SF Billing fields (blng__) detected on OrderItem — indicates Salesforce Billing in use',
    countValue: null,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Quote-per-Opportunity behavior
  {
    id: '00000000-0000-4000-f000-000000000145',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage' as const,
    collectorName: 'usage',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Quote-per-Opportunity Behavior',
    artifactId: null,
    findingKey: 'usage:TransactionalObjectDetail:SBQQ__Quote__c:quotes_per_opp',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '18', label: 'Opps with quotes (90d)' },
      { type: 'count', value: '23', label: 'Quotes in window' },
      { type: 'count', value: '1.3', label: 'Avg quotes per Opp' },
      { type: 'count', value: '5', label: 'Non-primary quotes' },
      { type: 'count', value: '22%', label: 'Non-primary %' },
    ],
    notes: 'Avg 1.3 quotes/opp, 22% non-primary',
    countValue: 18,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Opportunity SBQQ formula fields
  {
    id: '00000000-0000-4000-f000-000000000146',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'usage' as const,
    collectorName: 'usage',
    artifactType: 'TransactionalObjectDetail',
    artifactName: 'Opportunity — SBQQ Formula Fields',
    artifactId: null,
    findingKey: 'usage:TransactionalObjectDetail:Opportunity:opp_sbqq_formulas',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '3', label: 'Formula fields referencing SBQQ' },
      { type: 'field-ref', value: 'CPQ_Total_Amount__c', label: 'Formula: CPQ Total Amount' },
      {
        type: 'field-ref',
        value: 'Primary_Quote_Status__c',
        label: 'Formula: Primary Quote Status',
      },
      { type: 'field-ref', value: 'Quote_Count__c', label: 'Formula: Quote Count' },
    ],
    notes: null,
    countValue: 3,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Account Renewal Model distribution
  {
    id: '00000000-0000-4000-f000-000000000147',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'settings' as const,
    collectorName: 'discovery',
    artifactType: 'CPQCapabilityDetection',
    artifactName: 'Account-Level Renewal Model Distribution',
    artifactId: null,
    findingKey: 'discovery:CPQCapabilityDetection:renewal_model_distribution:global',
    sourceType: 'object' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'count', value: '145', label: 'Renewal Model: Contract Based' },
      { type: 'count', value: '82', label: 'Renewal Model: Asset Based' },
    ],
    notes: 'Account renewal models: Contract Based (145), Asset Based (82)',
    countValue: 2,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },

  // V11 — Special Field Usage (sample)
  ...(
    [
      { field: 'SBQQ__AdditionalDiscountAmount__c', obj: 'SBQQ__Quote__c', count: 8 },
      { field: 'SBQQ__PartnerDiscount__c', obj: 'SBQQ__Quote__c', count: 0 },
      { field: 'SBQQ__AdditionalDiscount__c', obj: 'SBQQ__QuoteLine__c', count: 11 },
      { field: 'SBQQ__SpecialPrice__c', obj: 'SBQQ__QuoteLine__c', count: 5 },
    ] as const
  ).map(
    (sf, i) =>
      ({
        id: `00000000-0000-4000-f000-000000000${150 + i}`,
        runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
        domain: 'transactional-objects' as const,
        collectorName: 'transactional-objects',
        artifactType: 'SpecialFieldUsage',
        artifactName: sf.field,
        artifactId: null,
        findingKey: `transactional-objects:SpecialFieldUsage:${sf.obj}:${sf.field}`,
        sourceType: 'object' as const,
        riskLevel: null,
        complexityLevel: null,
        migrationRelevance: null,
        rcaTargetConcept: null,
        rcaMappingComplexity: null,
        evidenceRefs: [
          { type: 'field-ref', value: sf.field, label: 'Special Field' },
          { type: 'object-ref', value: sf.obj, label: 'Object' },
          { type: 'count', value: String(sf.count), label: 'Records with field populated' },
        ],
        notes: null,
        countValue: sf.count,
        textValue: null,
        createdAt: new Date('2026-04-10T12:00:00Z'),
      }) satisfies AssessmentFindingEntity
  ),

  // V11 — Twin Field Detection (sample)
  {
    id: '00000000-0000-4000-f000-000000000160',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'transactional-objects' as const,
    collectorName: 'transactional-objects',
    artifactType: 'TwinFieldDetection',
    artifactName: 'Twin Fields: SBQQ__Quote__c ↔ Order',
    artifactId: null,
    findingKey: 'transactional-objects:TwinFieldDetection:SBQQ__Quote__c:Order:twin_fields',
    sourceType: 'inferred' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'object-ref', value: 'SBQQ__Quote__c', label: 'Object A' },
      { type: 'object-ref', value: 'Order', label: 'Object B' },
      { type: 'count', value: '4', label: 'Twin Field Count' },
      { type: 'field-ref', value: 'Custom_Status__c', label: 'Twin Field Example' },
      { type: 'field-ref', value: 'Billing_Frequency__c', label: 'Twin Field Example' },
    ],
    notes:
      '4 org-owned custom fields with matching API names across SBQQ__Quote__c and Order. Detection method: API name convention matching.',
    countValue: 4,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
  {
    id: '00000000-0000-4000-f000-000000000161',
    runId: MOCK_IDS.ASSESSMENT_RUN_Q1,
    domain: 'transactional-objects' as const,
    collectorName: 'transactional-objects',
    artifactType: 'TwinFieldDetection',
    artifactName: 'Twin Fields: SBQQ__QuoteLine__c ↔ OrderItem',
    artifactId: null,
    findingKey: 'transactional-objects:TwinFieldDetection:SBQQ__QuoteLine__c:OrderItem:twin_fields',
    sourceType: 'inferred' as const,
    riskLevel: null,
    complexityLevel: null,
    migrationRelevance: null,
    rcaTargetConcept: null,
    rcaMappingComplexity: null,
    evidenceRefs: [
      { type: 'object-ref', value: 'SBQQ__QuoteLine__c', label: 'Object A' },
      { type: 'object-ref', value: 'OrderItem', label: 'Object B' },
      { type: 'count', value: '6', label: 'Twin Field Count' },
      { type: 'field-ref', value: 'Twinned_Discount__c', label: 'Twin Field Example' },
    ],
    notes:
      '6 org-owned custom fields with matching API names across SBQQ__QuoteLine__c and OrderItem. Detection method: API name convention matching.',
    countValue: 6,
    textValue: null,
    createdAt: new Date('2026-04-10T12:00:00Z'),
  },
];
