/**
 * Assessment Run Seed Data
 *
 * Two completed runs — one for each project with assessment data:
 * - Q1 Migration: completed with mock assessment data
 * - Phase 2: completed with real Salesforce extraction data (532 items)
 */
import type { AssessmentRunEntity } from '@revbrain/contract';
import { MOCK_IDS } from './constants.ts';
import { daysAgo, hoursAgo } from './helpers.ts';

export const SEED_ASSESSMENT_RUNS: readonly AssessmentRunEntity[] = [
  {
    id: MOCK_IDS.ASSESSMENT_RUN_Q1,
    projectId: MOCK_IDS.PROJECT_Q1_MIGRATION,
    organizationId: MOCK_IDS.ORG_ACME,
    connectionId: MOCK_IDS.SF_CONNECTION_ACME_SOURCE,
    status: 'completed',
    statusReason: null,
    mode: 'full',
    rawSnapshotMode: 'errors_only',
    progress: {
      discovery: { status: 'success', records: 33, durationMs: 4200 },
      catalog: { status: 'success', records: 179, durationMs: 5600 },
      pricing: { status: 'success', records: 120, durationMs: 3800 },
      usage: { status: 'success', records: 73, durationMs: 8400 },
      dependencies: { status: 'success', records: 45, durationMs: 3200 },
      customizations: { status: 'success', records: 89, durationMs: 4100 },
      settings: { status: 'success', records: 12, durationMs: 1800 },
      'order-lifecycle': { status: 'success', records: 4, durationMs: 2100 },
      templates: { status: 'success', records: 24, durationMs: 2400 },
      approvals: { status: 'success', records: 18, durationMs: 1500 },
      integrations: { status: 'success', records: 50, durationMs: 3600 },
      localization: { status: 'success', records: 15, durationMs: 1200 },
    },
    orgFingerprint: {
      edition: 'Enterprise',
      cpqVersion: '232.2.0',
      orgId: '00D5g00000MOCK01',
      multiCurrency: false,
      personAccounts: false,
    },
    workerId: 'worker-seed-q1',
    leaseExpiresAt: null,
    lastHeartbeatAt: daysAgo(5),
    retryCount: 0,
    maxRetries: 2,
    idempotencyKey: null,
    dispatchedAt: daysAgo(5),
    startedAt: daysAgo(5),
    completedAt: daysAgo(5),
    failedAt: null,
    cancelRequestedAt: null,
    durationMs: 22900,
    apiCallsUsed: 187,
    recordsExtracted: 694,
    completenessPct: 100,
    error: null,
    createdBy: MOCK_IDS.USER_ACME_OWNER,
    createdAt: daysAgo(5),
  },
  {
    id: MOCK_IDS.ASSESSMENT_RUN_PHASE2,
    projectId: MOCK_IDS.PROJECT_PHASE2,
    organizationId: MOCK_IDS.ORG_ACME,
    connectionId: MOCK_IDS.SF_CONNECTION_ACME_SOURCE,
    status: 'completed',
    statusReason: null,
    mode: 'full',
    rawSnapshotMode: 'errors_only',
    progress: {
      discovery: { status: 'success', records: 33, durationMs: 3800 },
      catalog: { status: 'success', records: 217, durationMs: 6100 },
      pricing: { status: 'success', records: 55, durationMs: 3200 },
      usage: { status: 'success', records: 2, durationMs: 7500 },
      dependencies: { status: 'success', records: 72, durationMs: 2900 },
      customizations: { status: 'success', records: 49, durationMs: 3700 },
      settings: { status: 'success', records: 2, durationMs: 1600 },
      'order-lifecycle': { status: 'success', records: 1, durationMs: 1900 },
      templates: { status: 'success', records: 24, durationMs: 2100 },
      approvals: { status: 'success', records: 63, durationMs: 1300 },
      integrations: { status: 'success', records: 50, durationMs: 3100 },
      localization: { status: 'success', records: 15, durationMs: 1100 },
    },
    orgFingerprint: {
      edition: 'Enterprise',
      cpqVersion: '232.2.0',
      orgId: '00DSQ000000Gcls2AC',
      multiCurrency: false,
      personAccounts: false,
    },
    workerId: 'worker-seed-phase2',
    leaseExpiresAt: null,
    lastHeartbeatAt: hoursAgo(2),
    retryCount: 0,
    maxRetries: 2,
    idempotencyKey: null,
    dispatchedAt: hoursAgo(2),
    startedAt: hoursAgo(2),
    completedAt: hoursAgo(2),
    failedAt: null,
    cancelRequestedAt: null,
    durationMs: 22900,
    apiCallsUsed: 203,
    recordsExtracted: 547,
    completenessPct: 100,
    error: null,
    createdBy: MOCK_IDS.USER_ACME_OWNER,
    createdAt: hoursAgo(2),
  },
];
