import type { AuditLogEntity } from '@revbrain/contract';
import { MOCK_IDS } from './constants.ts';
import { daysAgo } from './helpers.ts';

let auditIdCounter = 1;
function auditId(): string {
  return `00000000-0000-4000-a000-000000000${String(500 + auditIdCounter++).padStart(3, '0')}`;
}

export const SEED_AUDIT_LOGS: readonly AuditLogEntity[] = [
  {
    id: auditId(),
    userId: MOCK_IDS.USER_SYSTEM_ADMIN,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'tenant.onboarded',
    targetUserId: MOCK_IDS.USER_ACME_OWNER,
    metadata: { tenantName: 'Acme Corp' },
    ipAddress: '10.0.0.1',
    userAgent: 'RevBrain Admin',
    createdAt: daysAgo(60),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_SYSTEM_ADMIN,
    organizationId: MOCK_IDS.ORG_BETA,
    action: 'tenant.onboarded',
    targetUserId: MOCK_IDS.USER_BETA_OWNER,
    metadata: { tenantName: 'Beta Industries' },
    ipAddress: '10.0.0.1',
    userAgent: 'RevBrain Admin',
    createdAt: daysAgo(30),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'user.invited',
    targetUserId: MOCK_IDS.USER_ACME_ADMIN,
    metadata: { email: 'sarah@acme.com', role: 'admin' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(45),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'user.invited',
    targetUserId: MOCK_IDS.USER_ACME_OPERATOR,
    metadata: { email: 'mike@acme.com', role: 'operator' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(40),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'project.created',
    targetUserId: null,
    metadata: { projectName: 'RCA Pilot' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(65),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'project.created',
    targetUserId: null,
    metadata: { projectName: 'Q1 Enterprise Product Catalog Migration' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(35),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_ADMIN,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'project.updated',
    targetUserId: null,
    metadata: { projectName: 'RCA Pilot', field: 'status', value: 'completed' },
    ipAddress: '192.168.1.20',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(7),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OPERATOR,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'project.updated',
    targetUserId: null,
    metadata: { projectName: 'Legacy Pricing Cleanup', field: 'notes' },
    ipAddress: '192.168.1.30',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(1),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'user.invited',
    targetUserId: MOCK_IDS.USER_ACME_PENDING,
    metadata: { email: 'pending@acme.com', role: 'operator' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(3),
  },
  {
    id: auditId(),
    userId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    action: 'project.created',
    targetUserId: null,
    metadata: { projectName: 'Phase 2 Migration' },
    ipAddress: '192.168.1.10',
    userAgent: 'Mozilla/5.0',
    createdAt: daysAgo(10),
  },
] as const;
