import type { UserEntity } from '@revbrain/contract';
import { MOCK_IDS } from './constants.ts';
import { daysAgo, hoursAgo } from './helpers.ts';

export const SEED_USERS: readonly UserEntity[] = [
  // System Admin (platform-level, no org)
  {
    id: MOCK_IDS.USER_SYSTEM_ADMIN,
    supabaseUserId: MOCK_IDS.USER_SYSTEM_ADMIN,
    organizationId: MOCK_IDS.ORG_ACME, // system admin still needs an org for middleware
    email: 'admin@revbrain.ai',
    fullName: 'System Admin',
    role: 'system_admin',
    isOrgAdmin: true,
    isActive: true,
    invitedBy: null,
    phoneNumber: null,
    jobTitle: 'Platform Administrator',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(90),
    activatedAt: daysAgo(90),
    lastLoginAt: hoursAgo(1),
  },

  // Acme Corp — org_owner
  {
    id: MOCK_IDS.USER_ACME_OWNER,
    supabaseUserId: MOCK_IDS.USER_ACME_OWNER,
    organizationId: MOCK_IDS.ORG_ACME,
    email: 'david@test.org',
    fullName: 'David Levy (Org Owner)',
    role: 'org_owner',
    isOrgAdmin: true,
    isActive: true,
    invitedBy: MOCK_IDS.USER_SYSTEM_ADMIN,
    phoneNumber: '+1-555-0101',
    jobTitle: 'VP Revenue Operations',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(60),
    activatedAt: daysAgo(59),
    lastLoginAt: hoursAgo(2),
  },

  // Acme Corp — admin
  {
    id: MOCK_IDS.USER_ACME_ADMIN,
    supabaseUserId: MOCK_IDS.USER_ACME_ADMIN,
    organizationId: MOCK_IDS.ORG_ACME,
    email: 'sarah@test.org',
    fullName: 'Sarah Cohen (Admin)',
    role: 'admin',
    isOrgAdmin: false,
    isActive: true,
    invitedBy: MOCK_IDS.USER_ACME_OWNER,
    phoneNumber: null,
    jobTitle: 'RevOps Manager',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(45),
    activatedAt: daysAgo(44),
    lastLoginAt: daysAgo(1),
  },

  // Acme Corp — operator
  {
    id: MOCK_IDS.USER_ACME_OPERATOR,
    supabaseUserId: MOCK_IDS.USER_ACME_OPERATOR,
    organizationId: MOCK_IDS.ORG_ACME,
    email: 'mike@test.org',
    fullName: 'Mike Johnson (Operator)',
    role: 'operator',
    isOrgAdmin: false,
    isActive: true,
    invitedBy: MOCK_IDS.USER_ACME_OWNER,
    phoneNumber: null,
    jobTitle: 'Migration Specialist',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(40),
    activatedAt: daysAgo(39),
    lastLoginAt: daysAgo(2),
  },

  // Acme Corp — reviewer
  {
    id: MOCK_IDS.USER_ACME_REVIEWER,
    supabaseUserId: MOCK_IDS.USER_ACME_REVIEWER,
    organizationId: MOCK_IDS.ORG_ACME,
    email: 'amy@test.org',
    fullName: 'Amy Chen (Reviewer)',
    role: 'reviewer',
    isOrgAdmin: false,
    isActive: true,
    invitedBy: MOCK_IDS.USER_ACME_ADMIN,
    phoneNumber: null,
    jobTitle: 'Business Analyst',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(30),
    activatedAt: daysAgo(29),
    lastLoginAt: daysAgo(3),
  },

  // Beta Industries — org_owner
  {
    id: MOCK_IDS.USER_BETA_OWNER,
    supabaseUserId: MOCK_IDS.USER_BETA_OWNER,
    organizationId: MOCK_IDS.ORG_BETA,
    email: 'lisa@test.org',
    fullName: 'Lisa Park',
    role: 'org_owner',
    isOrgAdmin: true,
    isActive: true,
    invitedBy: MOCK_IDS.USER_SYSTEM_ADMIN,
    phoneNumber: '+1-555-0201',
    jobTitle: 'Director of Operations',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(30),
    activatedAt: daysAgo(29),
    lastLoginAt: daysAgo(5),
  },

  // Beta Industries — operator
  {
    id: MOCK_IDS.USER_BETA_OPERATOR,
    supabaseUserId: MOCK_IDS.USER_BETA_OPERATOR,
    organizationId: MOCK_IDS.ORG_BETA,
    email: 'tom@test.org',
    fullName: 'Tom Wilson',
    role: 'operator',
    isOrgAdmin: false,
    isActive: true,
    invitedBy: MOCK_IDS.USER_BETA_OWNER,
    phoneNumber: null,
    jobTitle: 'Systems Analyst',
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(20),
    activatedAt: daysAgo(19),
    lastLoginAt: daysAgo(7),
  },

  // Acme Corp — invited but not yet activated (pending)
  {
    id: MOCK_IDS.USER_ACME_PENDING,
    supabaseUserId: MOCK_IDS.USER_ACME_PENDING,
    organizationId: MOCK_IDS.ORG_ACME,
    email: 'pending@test.org',
    fullName: 'Pending User',
    role: 'operator',
    isOrgAdmin: false,
    isActive: false,
    invitedBy: MOCK_IDS.USER_ACME_OWNER,
    phoneNumber: null,
    jobTitle: null,
    address: null,
    age: null,
    bio: null,
    avatarUrl: null,
    mobileNumber: null,
    preferences: null,
    metadata: null,
    createdAt: daysAgo(3),
    activatedAt: null,
    lastLoginAt: null,
  },
] as const;
