/**
 * EXT-CC1 — Field-Level Security introspection.
 *
 * The §8.3 audit + the v1.1 gaps-doc fix taught us that
 * `View All Data` does NOT override Field-Level Security: an
 * integration user with VAD but missing FLS read on a CPQ field
 * will silently fail to extract that field from any SOQL query —
 * the field is simply absent from the response with NO error.
 * This makes "we got 47 products" indistinguishable from "we got
 * 47 products and silently dropped 12 fields per record."
 *
 * This module runs as a pre-flight check at extraction start. It
 * queries `FieldPermissions` against the running user's effective
 * permission-set aggregate, compares against a static
 * `REQUIRED_FLS` map of fields the worker's collectors actually
 * read, and:
 *
 *   - **Hard-fails** the run when a base-object identifier (Id,
 *     Name, DeveloperName, NamespacePrefix) is unreadable. The
 *     extractor literally cannot function without these.
 *   - **Warns + degrades** when any other field is unreadable.
 *     The collector continues but the per-finding output for
 *     that object will be incomplete. The gap is surfaced via
 *     `metrics.flsGapCount` + a top-level `degradedInputs` entry.
 *
 * **Determinism note:** the gap list is sorted by (object, field)
 * before being emitted so re-runs against the same FLS state
 * produce byte-identical IRGraph metadata. The introspection
 * call itself is non-deterministic (queries SF) but its OUTPUT
 * is deterministic given identical input state.
 */

export interface FlsGap {
  object: string;
  field: string;
  severity: 'hard' | 'warn';
}

export interface FlsIntrospectionResult {
  /** Total `(object, field)` pairs the collectors require. */
  requiredCount: number;
  /** All gaps detected, sorted by (object, field). */
  gaps: FlsGap[];
  /** True iff any hard-severity gap was found. */
  hasHardFailures: boolean;
}

/**
 * Identifier fields whose absence is a hard failure on every CPQ
 * object: without them the collectors cannot reference records
 * by id or correlate findings.
 */
const HARD_REQUIRED_FIELDS = new Set(['Id', 'Name', 'DeveloperName', 'NamespacePrefix']);

/**
 * Static map of `(object, field)` pairs the worker's collectors
 * project in their SOQL queries. This is the minimum coverage
 * baseline; missing entries cause silent under-extraction.
 *
 * Generated by hand from the existing collector queries. The
 * follow-up is to auto-extract this from the SOQL builders so
 * the map stays in sync as collectors evolve. For now, the cost
 * of staleness is "we don't catch every gap" — still strictly
 * better than the pre-fix state of catching ZERO gaps.
 */
export const REQUIRED_FLS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  // Catalog (catalog.ts)
  Product2: [
    'Id',
    'Name',
    'ProductCode',
    'Family',
    'IsActive',
    'SBQQ__ConfigurationType__c',
    'SBQQ__SubscriptionType__c',
    'SBQQ__BillingFrequency__c',
    'SBQQ__PricingMethod__c',
  ],
  // Pricing (pricing.ts)
  SBQQ__PriceRule__c: [
    'Id',
    'Name',
    'SBQQ__Active__c',
    'SBQQ__EvaluationOrder__c',
    'SBQQ__ConditionsMet__c',
    'SBQQ__EvaluationEvent__c',
    'SBQQ__LookupObject__c',
  ],
  SBQQ__ProductRule__c: [
    'Id',
    'Name',
    'SBQQ__Active__c',
    'SBQQ__EvaluationEvent__c',
    'SBQQ__Type__c',
    'SBQQ__ConditionsMet__c',
  ],
  SBQQ__DiscountSchedule__c: ['Id', 'Name', 'SBQQ__Type__c', 'SBQQ__AggregationScope__c'],
  SBQQ__CustomScript__c: ['Id', 'Name', 'SBQQ__Code__c', 'SBQQ__Group__c', 'SBQQ__GroupFields__c'],
  // Quote / order (catalog/order-lifecycle)
  SBQQ__Quote__c: ['Id', 'Name', 'SBQQ__NetAmount__c', 'SBQQ__Status__c', 'SBQQ__Account__c'],
  SBQQ__QuoteLine__c: [
    'Id',
    'SBQQ__Quote__c',
    'SBQQ__Product__c',
    'SBQQ__NetTotal__c',
    'SBQQ__Quantity__c',
  ],
});

/**
 * Aggregate the running user's effective FLS read permissions
 * across every assigned permission set. The caller is the SF
 * REST API client; we keep the helper interface narrow so the
 * unit tests can stub it without mocking the entire client.
 */
export interface FieldPermissionsRow {
  Field: string; // e.g. 'Product2.IsActive'
  PermissionsRead: boolean;
}

export interface FlsQueryFn {
  (objects: readonly string[]): Promise<FieldPermissionsRow[]>;
}

/**
 * Run the FLS introspection over the static REQUIRED_FLS map
 * using the supplied query function. Returns the gap list +
 * hard-failure flag.
 *
 * @param queryFn function that accepts the object names to scan
 *                and returns the union of FieldPermissions rows
 *                for them. The caller decides whether to chunk,
 *                page, or batch — the introspect helper just
 *                consumes the result.
 */
export async function introspectFls(
  queryFn: FlsQueryFn,
  required: Readonly<Record<string, readonly string[]>> = REQUIRED_FLS
): Promise<FlsIntrospectionResult> {
  const objects = Object.keys(required).sort();
  const rows = await queryFn(objects);

  // Build a Set of fully-qualified `Object.Field` keys the user
  // has READ permission on.
  const granted = new Set<string>();
  for (const row of rows) {
    if (row.PermissionsRead) granted.add(row.Field);
  }

  const gaps: FlsGap[] = [];
  let requiredCount = 0;
  for (const [object, fields] of Object.entries(required)) {
    for (const field of fields) {
      requiredCount++;
      const key = `${object}.${field}`;
      // Identifiers like `Id` and `Name` are sometimes not in
      // FieldPermissions at all (they're never restrictable in
      // standard FLS). Treat absence in the granted set as a
      // gap ONLY for the non-hard-required fields. Hard-required
      // fields are presumed available unless explicitly DENIED;
      // since we cannot distinguish "not in FieldPermissions
      // because it's never restrictable" from "not in the row
      // set because the user has no read", we err on the side
      // of the user — only emit a gap for fields that ARE in
      // FieldPermissions but lack PermissionsRead.
      if (!granted.has(key)) {
        // Check whether the row exists at all (i.e. it CAN be
        // restricted). If the row simply isn't returned, the
        // field is unrestricted by definition.
        const rowExists = rows.some((r) => r.Field === key);
        if (!rowExists) continue;
        gaps.push({
          object,
          field,
          severity: HARD_REQUIRED_FIELDS.has(field) ? 'hard' : 'warn',
        });
      }
    }
  }

  // Determinism: sort gaps so re-runs against the same FLS
  // state produce byte-identical output.
  gaps.sort((a, b) => {
    if (a.object !== b.object) return a.object.localeCompare(b.object);
    return a.field.localeCompare(b.field);
  });

  return {
    requiredCount,
    gaps,
    hasHardFailures: gaps.some((g) => g.severity === 'hard'),
  };
}
