/**
 * Report Template — assembles all sections into a complete HTML document.
 *
 * Each section is a pure function: ReportData → HTML string.
 * CSS is inlined for PDF rendering (no external stylesheets).
 */

import type { ReportData } from '../assembler.ts';
import { reportStyles } from './styles.ts';
import { escapeHtml, badge, scoreBar, severity, table } from './partials/helpers.ts';

export function renderReport(data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${reportStyles}</style>
</head>
<body>
  ${renderCover(data)}
  ${renderScope(data)}
  ${renderExecutiveSummary(data)}
  ${renderGlance(data)}
  ${renderSettings(data)}
  ${renderLifecycle(data)}
  ${renderConfigDomain(data)}
  ${renderUsage(data)}
  ${renderDataQuality(data)}
  ${renderCustomCode(data)}
  ${renderHotspots(data)}
  ${renderAppendixA(data)}
  ${renderAppendixB(data)}
  ${renderAppendixCD(data)}
</body>
</html>`;
}

// ============================================================================
// Section 1: Cover Page
// ============================================================================

function renderCover(data: ReportData): string {
  return `
  <div class="cover">
    <h1>SALESFORCE CPQ<br/>ENVIRONMENT ASSESSMENT REPORT</h1>
    <h2>Current State Configuration & Usage Analysis<br/>90-Day Activity Window</h2>
    ${table(
      ['Field', 'Value'],
      [
        ['Client Name', escapeHtml(data.metadata.clientName)],
        ['Salesforce Org ID', escapeHtml(data.metadata.orgId)],
        ['Environment', escapeHtml(data.metadata.environment)],
        ['Assessment Date', escapeHtml(data.metadata.assessmentDate)],
        ['Assessment Period', escapeHtml(data.metadata.assessmentPeriod)],
        ['CPQ Package Version', escapeHtml(data.metadata.cpqVersion)],
        ['Report Generated By', escapeHtml(data.metadata.generatedBy)],
        ['Classification', 'Confidential'],
      ]
    )}
    <div class="section-footer">Generated by RevBrain CPQ Assessment Tool</div>
  </div>`;
}

// ============================================================================
// Section 2: Scope & Methodology
// ============================================================================

function renderScope(_data: ReportData): string {
  return `
  <div class="page-break">
    <h2>1. Scope & Methodology</h2>
    <h3>1.1 Assessment Scope</h3>
    <p>This report provides a current-state assessment of the Salesforce CPQ environment. It inventories all configuration objects, analyzes transactional usage and user behavior over the preceding 90 days, evaluates data quality and technical debt, and identifies areas of concentrated complexity.</p>

    <h3>1.2 Methodology</h3>
    <ol>
      <li><strong>Metadata Extraction:</strong> CPQ configuration metadata extracted via Salesforce APIs.</li>
      <li><strong>Usage & Behavior Analysis:</strong> SOQL queries extract 90-day transactional data.</li>
      <li><strong>Data Quality Assessment:</strong> Automated analysis of field completeness and orphaned records.</li>
      <li><strong>Custom Code Scan:</strong> Identification of Apex classes, triggers, and flows referencing SBQQ objects.</li>
      <li><strong>Complexity Scoring:</strong> Fixed weighted model normalized against benchmark ranges.</li>
    </ol>

    <h3>1.3 Data Confidence Levels</h3>
    ${table(
      ['Level', 'Label', 'Definition'],
      [
        ['★★★', badge('Confirmed'), 'Directly extracted from Salesforce metadata or SOQL query.'],
        ['★★', badge('Estimated'), 'Derived from available metadata with reasonable inference.'],
        ['★', badge('Partial'), 'Based on incomplete extraction or sampling.'],
      ]
    )}
  </div>`;
}

// ============================================================================
// Section 3: Executive Summary
// ============================================================================

function renderExecutiveSummary(data: ReportData): string {
  const findingsRows = data.executiveSummary.keyFindings.map((f, i) => [
    String(i + 1),
    `<strong>${escapeHtml(f.title)}</strong>`,
    escapeHtml(f.detail),
    badge(f.confidence),
  ]);

  const scores = data.executiveSummary.complexityScores;

  return `
  <div class="page-break">
    <h2>2. Executive Summary</h2>
    <h3>2.1 Key Findings</h3>
    ${table(['#', 'Finding', 'Detail', 'Confidence'], findingsRows)}

    <h3>2.2 Complexity Scores</h3>
    ${scoreBar('Overall Complexity', scores.overall)}
    ${scoreBar('Configuration Depth', scores.configurationDepth)}
    ${scoreBar('Pricing Logic', scores.pricingLogic)}
    ${scoreBar('Customization Level', scores.customizationLevel)}
    ${scoreBar('Data Volume & Usage', scores.dataVolumeUsage)}
    ${scoreBar('Technical Debt', scores.technicalDebt)}
  </div>`;
}

// ============================================================================
// Section 4: CPQ at a Glance
// ============================================================================

function renderGlance(data: ReportData): string {
  const sections = Object.entries(data.cpqAtAGlance);

  return `
  <div class="page-break">
    <h2>3. CPQ at a Glance</h2>
    <div class="glance-grid">
      ${sections
        .map(
          ([title, metrics]) => `
        <div class="glance-section">
          <h4>${escapeHtml(title)}</h4>
          ${table(
            ['Metric', 'Value', 'Conf.'],
            metrics.map((m) => [
              escapeHtml(m.label),
              `<strong>${escapeHtml(m.value)}</strong>`,
              badge(m.confidence),
            ])
          )}
        </div>
      `
        )
        .join('')}
    </div>
  </div>`;
}

// ============================================================================
// Section 5: Package Settings
// ============================================================================

function renderSettings(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>4. CPQ Package Settings</h2>
    <h3>4.1 Installed Packages</h3>
    ${
      data.packageSettings.installedPackages.length > 0
        ? table(
            ['Package', 'Namespace', 'Version', 'Status'],
            data.packageSettings.installedPackages.map((p) => [
              escapeHtml(p.name),
              escapeHtml(p.namespace),
              escapeHtml(p.version),
              escapeHtml(p.status),
            ])
          )
        : '<p><em>Package inventory available from Discovery collector.</em></p>'
    }

    <h3>4.2 Core CPQ Settings</h3>
    ${table(
      ['Setting', 'Value', 'Notes', 'Confidence'],
      data.packageSettings.coreSettings.map((s) => [
        escapeHtml(s.setting),
        `<strong>${escapeHtml(s.value)}</strong>`,
        escapeHtml(s.notes),
        badge(s.confidence),
      ])
    )}

    <h3>4.3 Plugins</h3>
    ${table(
      ['Plugin', 'Status', 'Notes', 'Confidence'],
      data.packageSettings.plugins.map((p) => [
        escapeHtml(p.plugin),
        `<strong>${escapeHtml(p.status)}</strong>`,
        escapeHtml(p.notes),
        badge(p.confidence),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 6: Quote Lifecycle
// ============================================================================

function renderLifecycle(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>5. Quote Lifecycle</h2>
    <ol>
      ${data.quoteLifecycle.map((s) => `<li>${escapeHtml(s.description)}</li>`).join('\n')}
    </ol>
  </div>`;
}

// ============================================================================
// Section 7: Configuration Domain
// ============================================================================

function renderConfigDomain(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>6. Configuration Domain Analysis</h2>

    <h3>6.1 Product Catalog</h3>
    ${
      data.configurationDomain.productCatalog.length > 0
        ? table(
            ['Category', 'Active', 'Inactive', 'Quoted 90d', '% Quoted', 'Conf.'],
            data.configurationDomain.productCatalog.map((c) => [
              escapeHtml(c.category),
              String(c.active),
              String(c.inactive),
              String(c.quoted90d),
              `${c.percentQuoted}%`,
              badge(c.confidence),
            ])
          )
        : '<p><em>Product catalog breakdown available from Catalog collector.</em></p>'
    }

    <h3>6.2 Price Rules</h3>
    ${table(
      ['Rule', 'Description', 'Complexity', 'Usage', 'Conf.'],
      data.configurationDomain.priceRules.map((r) => [
        escapeHtml(r.name),
        escapeHtml(r.description),
        severity(r.complexity),
        escapeHtml(r.usage),
        badge(r.confidence),
      ])
    )}

    <h3>6.3 Product Rules</h3>
    ${table(
      ['Rule', 'Description', 'Complexity', 'Conf.'],
      data.configurationDomain.productRules.map((r) => [
        escapeHtml(r.name),
        escapeHtml(r.description),
        severity(r.complexity),
        badge(r.confidence),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 8: Usage & Adoption
// ============================================================================

function renderUsage(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>7. Usage & Adoption Analysis</h2>

    <h3>7.1 90-Day Quoting Activity</h3>
    ${table(
      ['Metric', 'Value', 'Trend', 'Conf.'],
      data.usageAdoption.quotingActivity.map((m) => [
        escapeHtml(m.metric),
        `<strong>${escapeHtml(m.value)}</strong>`,
        escapeHtml(m.trend),
        badge(m.confidence),
      ])
    )}

    <h3>7.2 Conversion by Quote Size</h3>
    ${
      data.usageAdoption.conversionBySize.length > 0
        ? table(
            ['Size', '% Quotes', '% Revenue', 'Conversion', 'Conf.'],
            data.usageAdoption.conversionBySize.map((s) => [
              escapeHtml(s.segment),
              `${s.percentQuotes}%`,
              `${s.percentRevenue}%`,
              `${s.conversionRate}%`,
              badge(s.confidence),
            ])
          )
        : '<p><em>No conversion data available.</em></p>'
    }

    <h3>7.3 Discount Distribution</h3>
    ${
      data.usageAdoption.discountDistribution.length > 0
        ? table(
            ['Range', 'Count', '% Discounted'],
            data.usageAdoption.discountDistribution.map((d) => [
              escapeHtml(d.range),
              String(d.count),
              `${d.percent}%`,
            ])
          )
        : '<p><em>No discount data available.</em></p>'
    }

    ${
      data.usageAdoption.overrideAnalysis
        ? `
    <h3>7.4 Manual Price Overrides</h3>
    <p>${data.usageAdoption.overrideAnalysis.count} lines (${data.usageAdoption.overrideAnalysis.rate}%) with manual overrides. Revenue impact: $${data.usageAdoption.overrideAnalysis.revenueImpact.toLocaleString()}.</p>
    `
        : ''
    }

    <h3>7.5 User Behavior by Role</h3>
    ${
      data.usageAdoption.userBehavior.length > 0
        ? table(
            ['Role', 'Users', '% Quotes', 'Conv %'],
            data.usageAdoption.userBehavior.map((u) => [
              escapeHtml(u.profile),
              String(u.users),
              `${u.percentQuotes}%`,
              `${u.conversionRate}%`,
            ])
          )
        : '<p><em>No user behavior data available.</em></p>'
    }

    <h3>7.6 Top Quoted Products</h3>
    ${
      data.usageAdoption.topProducts.length > 0
        ? table(
            ['#', 'Product', 'Category', 'Quoted', '% Quotes'],
            data.usageAdoption.topProducts.map((p, i) => [
              String(i + 1),
              escapeHtml(p.name),
              escapeHtml(p.category),
              String(p.quotedCount),
              `${p.percentQuotes}%`,
            ])
          )
        : '<p><em>No product data available.</em></p>'
    }
  </div>`;
}

// ============================================================================
// Section 9: Data Quality & Technical Debt
// ============================================================================

function renderDataQuality(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>8. Data Quality & Technical Debt</h2>

    <h3>8.1 Flagged Areas</h3>
    ${table(
      ['Issue', 'Status', 'Detail'],
      data.dataQuality.flaggedAreas.map((f) => [
        escapeHtml(f.issue),
        `<strong>${escapeHtml(f.status)}</strong>`,
        escapeHtml(f.detail),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 10: Custom Code & Automation
// ============================================================================

function renderCustomCode(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>9. Custom Code & Automation Inventory</h2>

    <h3>9.1 Apex Classes Referencing SBQQ</h3>
    ${table(
      ['Class Name', 'Lines', 'Purpose', 'Origin'],
      data.customCode.apexClasses.map((a) => [
        escapeHtml(a.name),
        String(a.lines),
        escapeHtml(a.purpose),
        escapeHtml(a.origin),
      ])
    )}

    <h3>9.2 Triggers & Flows</h3>
    ${table(
      ['Component', 'Type', 'Object', 'Status'],
      data.customCode.triggersFlows.map((t) => [
        escapeHtml(t.name),
        escapeHtml(t.type),
        escapeHtml(t.object),
        escapeHtml(t.status),
      ])
    )}

    <h3>9.3 Validation Rules</h3>
    ${table(
      ['Object', 'Rule', 'Status', 'Complexity'],
      data.customCode.validationRules.map((v) => [
        escapeHtml(v.object),
        escapeHtml(v.rule),
        escapeHtml(v.status),
        severity(v.complexity),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 11: Complexity Hotspots
// ============================================================================

function renderHotspots(data: ReportData): string {
  if (data.complexityHotspots.length === 0) return '';
  return `
  <div class="page-break">
    <h2>10. Configuration Complexity Hotspots</h2>
    ${table(
      ['Hotspot', 'Severity', 'Analysis'],
      data.complexityHotspots.map((h) => [
        `<strong>${escapeHtml(h.name)}</strong>`,
        severity(h.severity),
        escapeHtml(h.analysis),
      ])
    )}
  </div>`;
}

// ============================================================================
// Appendix A: Object Inventory
// ============================================================================

function renderAppendixA(data: ReportData): string {
  if (data.appendixA.length === 0) return '';
  return `
  <div class="page-break">
    <h2>Appendix A: Configuration Object Inventory</h2>
    ${table(
      ['ID', 'Object(s)', 'API Name', 'Count', 'Complexity', 'Conf.'],
      data.appendixA.map((a) => [
        String(a.id),
        escapeHtml(a.objectName),
        `<code>${escapeHtml(a.apiName)}</code>`,
        String(a.count),
        severity(a.complexity),
        badge(a.confidence),
      ])
    )}
  </div>`;
}

// ============================================================================
// Appendix B: Reports & Dashboards
// ============================================================================

function renderAppendixB(data: ReportData): string {
  if (data.appendixB.length === 0) return '';
  return `
  <div class="page-break">
    <h2>Appendix B: CPQ Reports & Dashboards</h2>
    ${table(
      ['Report', 'Description'],
      data.appendixB.map((r) => [escapeHtml(r.name), escapeHtml(r.description)])
    )}
  </div>`;
}

// ============================================================================
// Appendix C+D: Glossary + Extraction Coverage
// ============================================================================

function renderAppendixCD(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>Appendix C: Glossary</h2>
    ${table(
      ['Term', 'Definition'],
      [
        ['CPQ', 'Configure, Price, Quote — Salesforce quoting application (SBQQ)'],
        ['RCA', 'Revenue Cloud Advanced — next-generation Salesforce revenue platform'],
        ['SBQQ', 'Namespace prefix for CPQ managed package objects'],
        ['sbaa', 'Advanced Approvals managed package'],
        ['QCP', 'Quote Calculator Plugin — JavaScript custom calculation injection'],
      ]
    )}

    <h2>Appendix D: Extraction Coverage</h2>
    ${table(
      ['Category', 'Coverage', 'Notes'],
      data.appendixD.map((d) => [escapeHtml(d.category), badge(d.coverage), escapeHtml(d.notes)])
    )}
  </div>`;
}
