/**
 * Report Template — assembles all sections into a complete HTML document.
 *
 * Each section is a pure function: ReportData → HTML string.
 * CSS is inlined for PDF rendering (no external stylesheets).
 *
 * Updated: Redline mitigation R0–R2 (scoring methodology, tech debt,
 *          feature utilization, expanded scope, active filtering, coverage)
 */

import type { ReportData } from '../assembler.ts';
import { isSectionEnabled } from '../assembler.ts';
import { reportStyles } from './styles.ts';
import { escapeHtml, badge, scoreBar, severity, table } from './partials/helpers.ts';
import {
  renderCheckboxTable,
  renderBinaryCheckboxTable,
  renderDenominatorFootnote,
} from './partials/checkbox.ts';
import { renderSummaryBoxPair } from './partials/summary-box.ts';

export function renderReport(data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${reportStyles}</style>
</head>
<body>
  ${renderCover(data)}
  ${renderBanners(data)}
  ${renderScope(data)}
  ${renderExecutiveSummary(data)}
  ${renderGlance(data)}
  ${renderSettings(data)}
  ${renderLifecycle(data)}
  ${renderSection6Header(data)}
  ${renderProductCatalog(data)}
  ${isSectionEnabled('6.2', data) ? renderProductDeepDive(data) : ''}
  ${renderPriceRules(data)}
  ${renderProductRules(data)}
  ${renderDiscountSchedules(data)}
  ${isSectionEnabled('6.6', data) ? renderBundlesDeepDive(data) : ''}
  ${renderApprovalsAndDocs(data)}
  ${renderUsage(data)}
  ${renderDataQuality(data)}
  ${renderCustomCode(data)}
  ${isSectionEnabled('10', data) ? renderRelatedFunctionality(data) : ''}
  ${renderHotspots(data)}
  ${renderAppendixA(data)}
  ${renderAppendixB(data)}
  ${renderAppendixCD(data)}
  ${isSectionEnabled('appendixE', data) ? renderAppendixE(data) : ''}
</body>
</html>`;
}

// ============================================================================
// Section 1: Cover Page
// ============================================================================

function renderCover(data: ReportData): string {
  const rows: string[][] = [
    ['Client Name', escapeHtml(data.metadata.clientName)],
    ['Salesforce Org ID', escapeHtml(data.metadata.orgId)],
    ['Environment', escapeHtml(data.metadata.environment)],
    ['Assessment Date', escapeHtml(data.metadata.assessmentDate)],
    ['Assessment Period', escapeHtml(data.metadata.assessmentPeriod)],
    ['CPQ Package Version', escapeHtml(data.metadata.cpqVersion)],
    [
      'Adv. Approvals Version',
      data.metadata.sbaaVersion ? escapeHtml(data.metadata.sbaaVersion) : 'Not installed',
    ],
    ['Document Version', escapeHtml(data.metadata.documentVersion)],
    ['Report Generated By', escapeHtml(data.metadata.generatedBy)],
    ['Classification', 'Confidential'],
  ];

  return `
  <div class="cover">
    <h1>SALESFORCE CPQ<br/>ENVIRONMENT ASSESSMENT REPORT</h1>
    <h2>Current State Configuration & Usage Analysis</h2>
    ${table(['Field', 'Value'], rows)}
    <div class="section-footer">Generated by RevBrain CPQ Assessment Tool</div>
  </div>`;
}

// ============================================================================
// Section 2: Scope & Methodology
// ============================================================================

function renderScope(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>1. Scope & Methodology</h2>
    <p><em>Audience: This report is designed for review of current-state CPQ complexity prior to planning.</em></p>

    <h3>1.1 Assessment Scope</h3>
    <p>This report provides a current-state assessment of the Salesforce CPQ environment. The following areas were assessed:</p>
    <ul>
      <li>CPQ configuration objects (products, bundles, options, constraints, attributes)</li>
      <li>Pricing rules, discount schedules, and custom scripts</li>
      <li>CPQ package settings and plugin configuration</li>
      <li>Quote templates and document generation</li>
      <li>Advanced approval rules and workflows</li>
      <li>90-day transactional usage patterns and trends</li>
      <li>User behavior and adoption metrics</li>
      <li>Discount and override patterns</li>
      <li>Data quality and field completeness</li>
      <li>Technical debt indicators (dormant configs, duplicate rules)</li>
      <li>Custom code: Apex, triggers, flows referencing CPQ objects</li>
      <li>Complexity scoring across 5 weighted dimensions</li>
      <li>Quote lifecycle and integration touchpoints</li>
    </ul>

    <h3>1.2 Methodology</h3>
    <ol>
      <li><strong>Metadata Extraction:</strong> CPQ configuration metadata extracted via Salesforce REST, Tooling, and Metadata APIs.</li>
      <li><strong>Usage & Behavior Analysis:</strong> SOQL queries extract 90-day transactional data including quotes, quote lines, orders, and user activity.</li>
      <li><strong>Data Quality Assessment:</strong> Automated analysis of field completeness, orphaned records, and duplicate detection.</li>
      <li><strong>Custom Code Scan:</strong> Identification of Apex classes, triggers, and flows referencing SBQQ objects via namespace scan.</li>
      <li><strong>Complexity Scoring:</strong> Fixed weighted model (see Section 2.3) normalized against benchmark ranges.</li>
    </ol>

    ${data.metadata.lowVolumeWarning ? `<p><strong>⚠ ${escapeHtml(data.metadata.lowVolumeWarning)}</strong></p>` : ''}

    <h3>1.3 Data Confidence Levels</h3>
    ${table(
      ['Level', 'Label', 'Definition'],
      [
        ['★★★', badge('Confirmed'), 'Directly extracted from Salesforce metadata or SOQL query.'],
        ['★★', badge('Estimated'), 'Derived from available metadata with reasonable inference.'],
        ['★', badge('Partial'), 'Based on incomplete extraction or sampling.'],
        [
          '—',
          badge('Not extracted'),
          'Extraction not attempted or collector did not produce results.',
        ],
      ]
    )}
  </div>`;
}

// ============================================================================
// Section 3: Executive Summary
// ============================================================================

function renderExecutiveSummary(data: ReportData): string {
  const findingsRows = data.executiveSummary.keyFindings.map((f, i) => [
    String(i + 1),
    `<strong>${escapeHtml(f.title)}</strong>`,
    escapeHtml(f.detail),
    badge(f.confidence),
  ]);

  const scores = data.executiveSummary.complexityScores;

  return `
  <div class="page-break">
    <h2>2. Executive Summary</h2>
    <h3>2.1 Key Findings</h3>
    ${table(['#', 'Finding', 'Detail', 'Confidence'], findingsRows)}

    <h3>2.2 Complexity Scores</h3>
    ${scoreBar('Overall Complexity', scores.overall)}
    ${scoreBar('Configuration Depth', scores.configurationDepth)}
    ${scoreBar('Pricing Logic', scores.pricingLogic)}
    ${scoreBar('Customization Level', scores.customizationLevel)}
    ${scoreBar('Data Volume & Usage', scores.dataVolumeUsage)}
    ${scoreBar('Technical Debt', scores.technicalDebt)}
    <p><em>Scores are directional indicators of relative complexity, not absolute measures.</em></p>

    ${
      data.complexityHotspots.length > 0
        ? `
    <h3>2.4 Complexity Hotspots (Summary)</h3>
    <p><em>Top complexity areas identified — see Section 11 for full analysis.</em></p>
    ${table(
      ['Hotspot', 'Severity'],
      data.complexityHotspots
        .slice(0, 5)
        .map((h) => [`<strong>${escapeHtml(h.name)}</strong>`, severity(h.severity)])
    )}`
        : ''
    }

    <h3>2.3 Scoring Methodology</h3>
    ${table(
      ['Dimension', 'Weight', 'Score', 'Tier', 'Drivers'],
      data.executiveSummary.scoringMethodology.map((m) => {
        const tier =
          m.score <= 25 ? 'Low' : m.score <= 50 ? 'Moderate' : m.score <= 75 ? 'High' : 'Very High';
        return [
          escapeHtml(m.dimension),
          `${m.weight}%`,
          `${m.score}/100`,
          tier,
          `${escapeHtml(m.drivers)}<br/><em style="font-size:0.9em;color:#555;">${escapeHtml(m.rationale)}</em>`,
        ];
      })
    )}
  </div>`;
}

// ============================================================================
// Section 4: CPQ at a Glance
// ============================================================================

function renderGlance(data: ReportData): string {
  const sections = Object.entries(data.cpqAtAGlance);
  const confSummary = data.dataConfidenceSummary;

  return `
  <div class="page-break">
    <h2>3. CPQ at a Glance</h2>
    ${confSummary ? `<p><em>Data confidence summary: approximately ${confSummary.confirmed}% Confirmed, ${confSummary.estimated}% Estimated, ${confSummary.partial}% Partial.</em></p>` : ''}
    <div class="glance-grid">
      ${sections
        .map(
          ([title, metrics]) => `
        <div class="glance-section">
          <h4>${escapeHtml(title)}</h4>
          ${table(
            ['Metric', 'Value', 'Conf.'],
            metrics.map((m) => [
              escapeHtml(m.label),
              `<strong>${escapeHtml(m.value)}</strong>`,
              badge(m.confidence),
            ])
          )}
          ${
            title === 'Product Catalog' &&
            metrics.some((m) => m.label === 'Bundle-capable Products' && m.value !== '0')
              ? `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>Bundle-capable = products with SBQQ__ConfigurationType__c set. This is a metadata capability flag, not a count of fully configured bundles with nested options.</em></p>`
              : ''
          }
        </div>
      `
        )
        .join('')}
    </div>
  </div>`;
}

// ============================================================================
// Section 5: Package Settings
// ============================================================================

function renderSettings(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>4. CPQ Package Settings</h2>
    <h3>4.1 Installed Packages</h3>
    ${
      data.packageSettings.installedPackages.length > 0
        ? table(
            ['Package', 'Namespace', 'Version', 'Status'],
            data.packageSettings.installedPackages.map((p) => [
              escapeHtml(p.name),
              escapeHtml(p.namespace),
              escapeHtml(p.version),
              escapeHtml(p.status),
            ])
          )
        : '<p><em>Package inventory available from Discovery collector.</em></p>'
    }

    <h3>4.2 Core CPQ Settings</h3>
    ${table(
      ['Setting', 'Value', 'Notes', 'Confidence'],
      data.packageSettings.coreSettings.map((s) => [
        escapeHtml(s.setting),
        `<strong>${escapeHtml(s.value)}</strong>`,
        escapeHtml(s.notes),
        badge(s.confidence),
      ])
    )}

    <h3>4.3 Plugins</h3>
    ${table(
      ['Plugin', 'Status', 'Notes', 'Confidence'],
      data.packageSettings.plugins.map((p) => [
        escapeHtml(p.plugin),
        `<strong>${escapeHtml(p.status)}</strong>`,
        escapeHtml(p.notes),
        badge(p.confidence),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 6: Quote Lifecycle
// ============================================================================

function renderLifecycle(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>5. Quote Lifecycle</h2>
    <p><em>The following lifecycle is derived from detected configuration patterns. Step sequence and frequency are inferred from metadata and have not been verified through direct process observation.</em></p>
    <ol>
      ${data.quoteLifecycle.map((s) => `<li>${escapeHtml(s.description)}</li>`).join('\n')}
    </ol>
  </div>`;
}

// ============================================================================
// Section 6: Configuration Domain — split into numbered sub-sections so that
// the conditional T2 Deep Dives (6.2, 6.6) can be interleaved at the correct
// positions per template V2.1. Spec order:
//   6.1 Product Catalog · 6.2 Product Deep Dive (T2) · 6.3 Price Rules ·
//   6.4 Product Rules · 6.5 Discount Schedules · 6.6 Bundles Deep Dive (T2) ·
//   6.7 Approvals & Document Generation
// ============================================================================

function renderSection6Header(_data: ReportData): string {
  return `<div class="page-break"><h2>6. Configuration Domain Analysis</h2></div>`;
}

function renderProductCatalog(data: ReportData): string {
  const dormant = data.configurationDomain.dormantFamilies;
  return `
  <div>
    <h3>6.1 Product Catalog</h3>
    ${
      data.configurationDomain.productCatalog.length > 0
        ? table(
            ['Category', 'Active', 'Inactive', 'Quoted 90d', '% Quoted', 'Conf.'],
            data.configurationDomain.productCatalog.map((c) => [
              escapeHtml(c.category),
              String(c.active),
              String(c.inactive),
              String(c.quoted90d),
              escapeHtml(c.percentQuoted),
              badge(c.confidence),
            ])
          ) +
          `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>% Quoted = products quoted in 90-day window &divide; active products in category.</em></p>`
        : '<p><em>Product catalog breakdown available from Catalog collector.</em></p>'
    }
    ${
      dormant.length > 0
        ? `<p><em>${dormant.length} of ${data.configurationDomain.productCatalog.length} product families show zero quoting activity in the 90-day window — including ${dormant
            .slice(0, 3)
            .map((d) => d.name)
            .join(
              ', '
            )}${dormant.length > 3 ? ', and others' : ''}. This may indicate dormant catalog segments, seasonal patterns, or a narrow active use-case.</em></p>`
        : ''
    }
  </div>`;
}

function renderPriceRules(data: ReportData): string {
  const prs = data.configurationDomain.priceRuleSummary;
  return `
  <div>
    <h3>6.3 Price Rules</h3>
    <p><em>${escapeHtml(data.configurationDomain.activePriceRuleSummary)}</em></p>
    <p>${prs.active} of ${prs.total} rules active. ${prs.highComplexity} high-complexity (4+ eval events). ${prs.inactive} inactive rules${prs.stale > 0 ? `, ${prs.stale} stale/test flagged as technical debt` : ''}.</p>
    ${(() => {
      // W1-7 (SI feedback): Sort Active first (high→low complexity), then Inactive
      const complexityRank: Record<string, number> = { high: 0, medium: 1, low: 2, '—': 3 };
      const sorted = [...data.configurationDomain.priceRules].sort((a, b) => {
        const aActive = a.status === 'Active' ? 0 : 1;
        const bActive = b.status === 'Active' ? 0 : 1;
        if (aActive !== bActive) return aActive - bActive;
        const aCx = complexityRank[a.complexity.toLowerCase()] ?? 3;
        const bCx = complexityRank[b.complexity.toLowerCase()] ?? 3;
        return aCx - bCx;
      });
      return table(
        ['Rule', 'Description', 'Complexity', 'Status', 'Conf.'],
        sorted.map((r) => [
          escapeHtml(r.name),
          escapeHtml(r.description),
          severity(r.complexity),
          escapeHtml(r.status),
          badge(r.confidence),
        ])
      );
    })()}
  </div>`;
}

function renderProductRules(data: ReportData): string {
  const prodrs = data.configurationDomain.productRuleSummary;
  return `
  <div>
    <h3>6.4 Product Rules</h3>
    <p><em>${escapeHtml(data.configurationDomain.activeProductRuleSummary)}</em></p>
    <p>${prodrs.selection} Selection, ${prodrs.alert} Alert, ${prodrs.validation} Validation, ${prodrs.filter} Filter rules active. ${prodrs.inactive} inactive${prodrs.stale > 0 ? `, ${prodrs.stale} stale/test flagged` : ''}.</p>
    ${(() => {
      // W1-8 (SI feedback): Sort Active by Type, then Inactive by Type
      const typeOrder: Record<string, number> = {
        Selection: 0,
        Alert: 1,
        Validation: 2,
        Filter: 3,
      };
      const sorted = [...data.configurationDomain.productRules].sort((a, b) => {
        const aActive = a.status === 'Active' ? 0 : 1;
        const bActive = b.status === 'Active' ? 0 : 1;
        if (aActive !== bActive) return aActive - bActive;
        const aType = typeOrder[a.type] ?? 99;
        const bType = typeOrder[b.type] ?? 99;
        return aType - bType;
      });
      return table(
        ['Rule', 'Type', 'Description', 'Complexity', 'Status', 'Conf.'],
        sorted.map((r) => [
          escapeHtml(r.name),
          escapeHtml(r.type),
          escapeHtml(r.description),
          severity(r.complexity),
          escapeHtml(r.status),
          badge(r.confidence),
        ])
      );
    })()}
    ${
      data.configurationDomain.productRules.some((r) => r.complexity === '—')
        ? `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>"—" in Complexity column = structural complexity not extracted. Requires condition/action scope analysis beyond current metadata extraction.</em></p>`
        : ''
    }
  </div>`;
}

function renderDiscountSchedules(data: ReportData): string {
  if (data.configurationDomain.discountScheduleAnalysis.length === 0) return '';
  return `
  <div>
    <h3>6.5 Discount Schedules</h3>
    <p><em>${data.configurationDomain.discountScheduleTotalCount} total schedules: ${data.configurationDomain.discountScheduleUniqueCount} unique names. ${data.configurationDomain.discountScheduleDuplicateDetail || 'No duplicates detected.'}</em></p>
    ${table(
      ['Schedule Name', 'Status', 'Cross Products', 'Cross Orders'],
      data.configurationDomain.discountScheduleAnalysis.map((d) => [
        escapeHtml(d.name),
        d.isDuplicate ? '<strong>⚠ Duplicate</strong>' : 'Unique',
        d.crossProducts ? '<strong>Yes</strong>' : 'No',
        d.crossOrders ? '<strong>Yes</strong>' : 'No',
      ])
    )}
    ${data.configurationDomain.discountScheduleAnalysis.some((d) => d.crossProducts || d.crossOrders) ? '<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>Cross Products/Orders = TRUE indicates discounts calculated across multiple records — adds complexity for RCA conversion.</em></p>' : ''}
  </div>`;
}

// ============================================================================
// Section 8: Usage & Adoption
// ============================================================================

function renderUsage(data: ReportData): string {
  const lowVol = data.usageAdoption.isLowVolume;
  return `
  <div class="page-break">
    <h2>7. Usage & Adoption Analysis</h2>
    ${lowVol ? '<p><strong>⚠ Low-volume data — results may not be statistically meaningful.</strong></p>' : ''}

    <h3>7.1 90-Day Quoting Activity</h3>
    ${table(
      ['Metric', 'Value', 'Trend', 'Conf.'],
      data.usageAdoption.quotingActivity.map((m) => [
        escapeHtml(m.metric),
        `<strong>${escapeHtml(m.value)}</strong>`,
        escapeHtml(m.trend),
        badge(m.confidence),
      ])
    )}

    <h3>7.2 Conversion by Quote Size</h3>
    ${
      data.usageAdoption.conversionBySize.length > 0
        ? table(
            ['Size', '% Quotes', '% Revenue', 'Conversion', 'Conf.'],
            data.usageAdoption.conversionBySize.map((s) => [
              escapeHtml(s.segment),
              `${s.percentQuotes}%`,
              `${s.percentRevenue}%`,
              `${s.conversionRate}%`,
              badge(s.confidence),
            ])
          ) +
          `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>% Quotes = quotes in segment &divide; total quotes (${data.counts.totalQuotes}). % Revenue = segment revenue &divide; total quoted revenue. Conversion = ordered quotes &divide; total quotes per segment.</em></p>`
        : '<p><em>No conversion data available.</em></p>'
    }

    <h3>7.3 Discount Distribution</h3>
    ${
      data.usageAdoption.discountDistribution.length > 0
        ? table(
            ['Range', 'Count', '% Discounted'],
            data.usageAdoption.discountDistribution.map((d) => [
              escapeHtml(d.range),
              String(d.count),
              escapeHtml(d.percent),
            ])
          ) +
          `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>% = quote lines in range &divide; total discounted quote lines. Count = number of discounted quote lines in each range.</em></p>`
        : '<p><em>No discount data available.</em></p>'
    }

    ${
      data.usageAdoption.overrideAnalysis
        ? `
    <h3>7.4 Manual Price Overrides</h3>
    <p>${data.usageAdoption.overrideAnalysis.count} lines (${data.usageAdoption.overrideAnalysis.rate}%) with manual overrides. Revenue impact: $${data.usageAdoption.overrideAnalysis.revenueImpact.toLocaleString()}.</p>
    `
        : ''
    }

    <h3>7.5 User Behavior by Role</h3>
    ${
      data.usageAdoption.userBehavior.length > 0
        ? table(
            ['Role', 'Users', '% Quotes', 'Conv %'],
            data.usageAdoption.userBehavior.map((u) => [
              escapeHtml(u.profile),
              String(u.users),
              `${u.percentQuotes}%`,
              `${u.conversionRate}%`,
            ])
          )
        : '<p><em>Insufficient user behavior data in assessment window.</em></p>'
    }

    <h3>7.6 Top Quoted Products</h3>
    ${
      data.usageAdoption.topProducts.length > 0
        ? table(
            ['#', 'Product', 'Category', 'Quoted', '% Quotes'],
            data.usageAdoption.topProducts.map((p, i) => [
              String(i + 1),
              escapeHtml(p.name),
              escapeHtml(p.category),
              String(p.quotedCount),
              escapeHtml(p.percentQuotes),
            ])
          ) +
          `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>% = distinct quotes containing product &divide; total quotes (${data.counts.totalQuotes})</em></p>`
        : '<p><em>No product quoting data available.</em></p>'
    }
  </div>`;
}

// ============================================================================
// Section 9: Data Quality & Technical Debt
// ============================================================================

function renderDataQuality(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>8. Data Quality & Technical Debt</h2>

    <h3>8.1 Flagged Areas</h3>
    ${
      data.dataQuality.flaggedAreas.length > 0
        ? table(
            ['Issue', 'Status', 'Detail'],
            data.dataQuality.flaggedAreas.map((f) => [
              escapeHtml(f.issue),
              `<strong>${escapeHtml(f.status)}</strong>`,
              escapeHtml(f.detail),
            ])
          )
        : '<p><em>No data quality flags detected.</em></p>'
    }

    <h3>8.2 Technical Debt Inventory</h3>
    ${
      data.dataQuality.technicalDebt.length > 0
        ? table(
            ['Category', 'Count', 'Detail'],
            data.dataQuality.technicalDebt.map((d) => [
              escapeHtml(d.category),
              String(d.count),
              escapeHtml(d.detail),
            ])
          )
        : '<p><em>No technical debt indicators detected.</em></p>'
    }

    <h3>8.3 Feature Utilization</h3>
    ${
      data.dataQuality.featureUtilization.length > 0
        ? table(
            ['Feature', 'Status', 'Detail'],
            data.dataQuality.featureUtilization.map((f) => [
              escapeHtml(f.feature),
              `<strong>${escapeHtml(f.status)}</strong>`,
              escapeHtml(f.detail),
            ])
          )
        : '<p><em>Feature utilization analysis requires collector data.</em></p>'
    }

    <h3>8.4 Field Completeness by Object</h3>
    ${
      data.dataQuality.fieldCompleteness.length > 0 &&
      data.dataQuality.fieldCompleteness.some((f) => f.totalFields > 0)
        ? table(
            [
              'Object',
              'Total Fields',
              'Fields >50% Populated',
              'Fields <5% Populated',
              'Quality Score',
            ],
            data.dataQuality.fieldCompleteness.map((f) => [
              escapeHtml(f.object),
              String(f.totalFields),
              String(f.above50pct),
              String(f.below5pct),
              escapeHtml(f.score),
            ])
          )
        : '<p><em>Field completeness analysis not extracted in current scope. Requires full schema and data scan.</em></p>'
    }
  </div>`;
}

// ============================================================================
// Section 10: Custom Code & Automation
// ============================================================================

function renderCustomCode(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>9. Custom Code & Automation Inventory</h2>

    <h3>9.1 Apex Classes Referencing SBQQ</h3>
    ${(() => {
      const testClasses = data.customCode.apexClasses.filter((a) =>
        a.purpose.toLowerCase().includes('test class')
      );
      const nonTestClasses = data.customCode.apexClasses.filter(
        (a) => !a.purpose.toLowerCase().includes('test class')
      );
      const testNote =
        testClasses.length > 0
          ? `<p><em>${data.customCode.apexClasses.length} Apex classes reference CPQ objects (${nonTestClasses.length} non-test + ${testClasses.length} test classes).</em></p>`
          : `<p><em>${data.customCode.apexClasses.length} Apex classes reference CPQ objects.</em></p>`;
      return testNote;
    })()}
    ${table(
      ['Class Name', 'Lines', 'Purpose', 'Origin'],
      data.customCode.apexClasses.map((a) => [
        escapeHtml(a.name),
        String(a.lines),
        escapeHtml(a.purpose),
        escapeHtml(a.origin),
      ])
    )}
    <p style="font-size:0.85em;color:#666;margin-top:4px;"><em>Methodology: Custom Apex classes whose source code contains references to the SBQQ namespace, identified via Salesforce Tooling API query. Includes both production code and test classes.</em></p>

    ${(() => {
      // §9.1a — Third-party (managed package) Apex summary.
      // Default view is one row per namespace (vendor). Per-class
      // detail is suppressed because managed-package Apex migrates
      // via a vendor plan, not via Apex rewrite. Internal diagnostic
      // runs may set `showThirdPartyApexDetail: true` which also
      // populates `thirdPartyApexDetail` below.
      if (data.customCode.thirdPartyApex.length === 0) return '';
      const total = data.customCode.thirdPartyApex.reduce((sum, ns) => sum + ns.classCount, 0);
      const summary = `
    <h3>9.1a Third-Party (Managed Package) Apex Classes</h3>
    <p><em>${total} managed-package Apex classes across ${data.customCode.thirdPartyApex.length} installed vendor package(s). These do not migrate via Apex rewrite — each vendor requires a separate migration plan.</em></p>
    ${table(
      ['Managed Package Namespace', 'Class Count', 'Total Lines'],
      data.customCode.thirdPartyApex.map((ns) => [
        escapeHtml(ns.namespace),
        String(ns.classCount),
        String(ns.totalLines),
      ])
    )}`;
      if (data.customCode.thirdPartyApexDetail.length === 0) return summary;
      return `${summary}
    <h4>9.1a.1 Per-Class Detail (Internal Diagnostic Mode)</h4>
    ${table(
      ['Class Name', 'Namespace', 'Lines'],
      data.customCode.thirdPartyApexDetail.map((c) => [
        escapeHtml(c.name),
        escapeHtml(c.namespace),
        String(c.lines),
      ])
    )}`;
    })()}

    ${(() => {
      // §9.1b — Active CPQ Plugins & Custom Scripts (aka §D.1 from the
      // mitigation plan, rendered here directly under §9 per customer
      // request to preserve the 11-section layout). Shows the three
      // things the customer cannot currently see:
      //
      //   1. Which customer-namespace Apex classes implement a CPQ
      //      plugin interface, with LOC and registration status
      //   2. Which QCP custom scripts exist in the org (by name + LOC)
      //   3. The full CPQ plugin slot table: every plugin interface
      //      CPQ supports and whether the tenant has wired Apex into it
      //
      // Source: flat findings via EXT-1.1 cpq_apex_plugin markers +
      // PluginActivation sidecar findings. See assembler.ts for the
      // extraction logic.
      const p = data.customCode.activePluginsAndScripts;
      if (
        p.apexPlugins.length === 0 &&
        p.qcpScripts.length === 0 &&
        p.interfaceActivation.length === 0
      )
        return '';
      const apexPluginsTable =
        p.apexPlugins.length > 0
          ? `
    <h4>9.1b.1 Apex Classes Implementing CPQ Plugin Interfaces</h4>
    ${table(
      ['Class Name', 'Interface(s)', 'Lines', 'Registration'],
      p.apexPlugins.map((pl) => [
        escapeHtml(pl.name),
        escapeHtml(pl.interfaceNames.join(', ')),
        String(pl.lines),
        escapeHtml(pl.registrationStatus),
      ])
    )}`
          : '';
      const qcpTable =
        p.qcpScripts.length > 0
          ? `
    <h4>9.1b.2 Quote Calculator Plugin (QCP) Custom Scripts</h4>
    ${table(
      ['Script Name', 'Lines'],
      p.qcpScripts.map((s) => [escapeHtml(s.name), String(s.lines)])
    )}`
          : '';
      const slotTable =
        p.interfaceActivation.length > 0
          ? `
    <h4>9.1b.3 CPQ Plugin Slot Activation</h4>
    <p><em>One row per CPQ plugin slot. "unset" = tenant uses the standard CPQ implementation; "active" = tenant has registered a custom Apex class.</em></p>
    ${table(
      ['Plugin Slot', 'Interface', 'Status'],
      p.interfaceActivation.map((ia) => [
        escapeHtml(ia.slot),
        escapeHtml(ia.interfaceName),
        escapeHtml(ia.status),
      ])
    )}`
          : '';
      return `
    <h3>9.1b Active CPQ Plugins & Custom Scripts</h3>
    <p><em>Everything below is extracted automatically from the tenant's Apex + CPQ plugin settings. Classes listed as "unset" exist in the org's codebase but are NOT wired into the CPQ plugin configuration — they will not run at quote time unless the tenant updates SBQQ__Plugin__c.</em></p>
    ${apexPluginsTable}${qcpTable}${slotTable}`;
    })()}

    <h3>9.2 Triggers & Flows</h3>
    ${
      data.counts.flowCountActive > 0
        ? `<p><em>${data.counts.flowCountActive} active flows (${data.counts.flowCountCpqRelated} CPQ-related${data.counts.flowCountActive > data.counts.flowCountCpqRelated ? `, ${data.counts.flowCountActive - data.counts.flowCountCpqRelated} additional active flows in org` : ''}). ${data.counts.flowCountActive} active flows shown. Total flows in org (including inactive and managed package flows) may be higher.</em></p>`
        : ''
    }
    ${
      data.customCode.triggersFlows.length > 0
        ? table(
            ['Component', 'Type', 'Object', 'Status'],
            data.customCode.triggersFlows.map((t) => [
              escapeHtml(t.name),
              escapeHtml(t.type),
              escapeHtml(t.object),
              escapeHtml(t.status),
            ])
          )
        : '<p><em>No triggers or flows detected.</em></p>'
    }

    <h3>9.3 Validation Rules</h3>
    ${
      data.customCode.validationRules.length > 0
        ? (() => {
            const objects = [
              ...new Set(data.customCode.validationRules.map((v) => v.object)),
            ].filter((o) => o && o !== 'CPQ Object');
            return `<p><em>${data.customCode.validationRules.length} validation rules across ${objects.length > 0 ? `${objects.length} CPQ-related objects (${objects.join(', ')})` : 'CPQ-related objects'}.</em></p>`;
          })()
        : ''
    }
    ${
      data.customCode.validationRules.length > 0
        ? table(
            ['Object', 'Rule', 'Status', 'Complexity'],
            data.customCode.validationRules.map((v) => [
              escapeHtml(v.object),
              escapeHtml(v.rule),
              escapeHtml(v.status),
              severity(v.complexity),
            ])
          )
        : '<p><em>No validation rules detected.</em></p>'
    }

    ${
      data.customCode.permissionSets.length > 0
        ? `
    <h3>9.4 CPQ Permission Sets</h3>
    ${table(
      ['Permission Set', 'Type', 'Namespace'],
      data.customCode.permissionSets.map((ps) => [
        escapeHtml(ps.name),
        escapeHtml(ps.type),
        escapeHtml(ps.namespace),
      ])
    )}`
        : ''
    }
  </div>`;
}

// ============================================================================
// Validation Banners (V1–V3 warnings, displayed at top of report)
// ============================================================================

function renderBanners(data: ReportData): string {
  if (!data.reportBanners || data.reportBanners.length === 0) return '';
  return `
  <div style="margin: 10px 0; padding: 12px; background: #fff3cd; border: 2px solid #ffc107; border-radius: 6px;">
    ${data.reportBanners.map((b) => `<p style="margin: 4px 0; font-weight: 600; color: #856404;">${escapeHtml(b)}</p>`).join('')}
  </div>`;
}

// ============================================================================
// Section 6.6: Approvals & Document Generation (renumbered from 6.4 — Task 0.3)
// ============================================================================

function renderApprovalsAndDocs(data: ReportData): string {
  const {
    customActions,
    advancedApprovalRules,
    approvalChains,
    approvalRules,
    quoteTemplates,
    documentGeneration,
  } = data.approvalsAndDocs;

  const hasAdvanced = advancedApprovalRules.length > 0;
  const hasCustomActions = customActions.length > 0;
  const hasContent =
    hasAdvanced || hasCustomActions || approvalRules.length > 0 || quoteTemplates.length > 0;

  return `
  <div class="page-break">
    <h2>6.7 Approvals & Document Generation</h2>

    <h3>6.7.1 Advanced Approval Rules (sbaa)</h3>
    ${
      hasAdvanced
        ? table(
            ['Rule Name', 'Target Object', 'Conditions', 'Status'],
            advancedApprovalRules.map((r) => [
              escapeHtml(r.name),
              escapeHtml(r.targetObject || '—'),
              String(r.conditions),
              escapeHtml(r.status),
            ])
          )
        : '<p><em>Advanced Approvals (sbaa) not detected. Custom action buttons listed below.</em></p>'
    }
    ${
      approvalChains.count > 0
        ? `<p>${approvalChains.count} approval chain(s) configured with ${approvalChains.approvers} approver(s).</p>`
        : ''
    }

    <h3>6.7.2 CPQ Custom Action Buttons</h3>
    ${
      hasCustomActions
        ? (() => {
            // W2-4 (SI feedback): Sort Active first, then by Location
            const sorted = [...customActions].sort((a, b) => {
              const aActive = a.status === 'Active' ? 0 : 1;
              const bActive = b.status === 'Active' ? 0 : 1;
              if (aActive !== bActive) return aActive - bActive;
              return a.location < b.location ? -1 : a.location > b.location ? 1 : 0;
            });
            return table(
              ['Action', 'Type', 'Location', 'Status'],
              sorted.map((a) => [
                escapeHtml(a.name),
                escapeHtml(a.type),
                escapeHtml(a.location),
                escapeHtml(a.status),
              ])
            );
          })()
        : '<p><em>No custom action buttons detected.</em></p>'
    }

    <h3>6.7.3 Standard Approval Processes</h3>
    ${
      approvalRules.length > 0
        ? table(
            ['Process', 'Target Object', 'Status'],
            approvalRules.map((r) => [
              escapeHtml(r.name),
              escapeHtml(r.object),
              escapeHtml(r.status),
            ])
          )
        : '<p><em>No standard approval processes detected on CPQ objects.</em></p>'
    }

    <h3>6.7.4 Quote Templates</h3>
    ${
      quoteTemplates.length > 0
        ? table(
            ['Template', 'Default', 'Last Modified'],
            quoteTemplates.map((t) => [
              escapeHtml(t.name),
              t.isDefault ? '<strong>Yes</strong>' : 'No',
              escapeHtml(t.lastModified || 'Unknown'),
            ])
          )
        : '<p><em>No quote templates detected.</em></p>'
    }

    ${quoteTemplates.length > 0 ? `<p style="font-size:0.85em;color:#666;margin-top:4px;"><em>Template complexity: ${data.counts.templateSectionCount ?? 'N/A'} template section(s) across all templates. ${data.counts.localizationCount ?? 0} localization record(s) — ${(data.counts.localizationCount ?? 0) > 0 ? 'translations add replication complexity.' : 'no localizations detected.'}</em></p>` : ''}

    <h3>6.7.5 Document Generation</h3>
    <p>${documentGeneration.usableTemplateCount} usable quote template(s)${documentGeneration.totalTemplateRecords !== documentGeneration.usableTemplateCount ? ` (${documentGeneration.totalTemplateRecords} total SBQQ__QuoteTemplate__c records, ${documentGeneration.usableTemplateCount} usable after excluding test/synthetic)` : ''}. DocuSign integration: <strong>${documentGeneration.docuSignActive ? 'Active' : 'Not detected'}</strong>.</p>
    ${!hasContent ? '<p><em>Approvals and document generation data requires Tier 2 collectors (templates, approvals) to complete successfully.</em></p>' : ''}
  </div>`;
}

// ============================================================================
// Section 11: Complexity Hotspots
// ============================================================================

function renderHotspots(data: ReportData): string {
  if (data.complexityHotspots.length === 0) return '';
  return `
  <div class="page-break">
    <h2>11. Complexity Hotspots</h2>
    ${table(
      ['Hotspot', 'Severity', 'Analysis'],
      data.complexityHotspots.map((h) => [
        `<strong>${escapeHtml(h.name)}</strong>`,
        severity(h.severity),
        escapeHtml(h.analysis),
      ])
    )}
  </div>`;
}

// ============================================================================
// Appendix A: Object Inventory
// ============================================================================

function renderAppendixA(data: ReportData): string {
  if (data.appendixA.length === 0) return '';

  const cpqObjects = data.appendixA.filter((a) => a.isCpqObject);
  const platformObjects = data.appendixA.filter((a) => !a.isCpqObject);

  // W1-10 (SI feedback): removed Phase column — it risks being read
  // as migration phasing, conflicting with the "no migration-readiness
  // language" rule. Extraction order is an internal implementation
  // detail, not useful to the SI reviewer.
  const renderTable = (items: typeof data.appendixA) =>
    table(
      ['ID', 'Object(s)', 'API Name', 'Count', 'Complexity', 'Conf.'],
      items.map((a, i) => [
        String(i + 1),
        escapeHtml(a.objectName),
        `<code>${escapeHtml(a.apiName)}</code>`,
        String(a.count),
        severity(a.complexity),
        badge(a.confidence),
      ])
    );

  return `
  <div class="page-break">
    <h2>Appendix A: Configuration Object Inventory</h2>

    <h3>A.1 CPQ Configuration Objects</h3>
    ${cpqObjects.length > 0 ? renderTable(cpqObjects) : '<p><em>No CPQ objects in inventory.</em></p>'}

    ${
      platformObjects.length > 0
        ? `
    <h3>A.2 Platform Metadata Summary</h3>
    ${renderTable(platformObjects)}`
        : ''
    }
  </div>`;
}

// ============================================================================
// Appendix B: Reports & Dashboards
// ============================================================================

function renderAppendixB(data: ReportData): string {
  if (data.appendixB.length === 0) return '';
  const summary = data.appendixBSummary;
  return `
  <div class="page-break">
    <h2>Appendix B: CPQ Reports & Dashboards</h2>
    <p><em>${summary.total} CPQ reports detected. ${summary.runLast12Mo} run in the last 12 months.${summary.staleCount > 0 ? ` ${summary.staleCount} not run in over 2 years — potential reporting technical debt.` : ''}</em></p>
    ${(() => {
      // W2-7 (SI feedback): Report ownership summary by folder
      const folderCounts = new Map<string, number>();
      for (const r of data.appendixB) {
        const folderMatch = r.description.match(/Folder:\s*([^—]+)/);
        const folder = folderMatch ? folderMatch[1]!.trim() : 'Unknown';
        folderCounts.set(folder, (folderCounts.get(folder) ?? 0) + 1);
      }
      if (folderCounts.size > 1) {
        return `<h4>Report Folder Distribution</h4>
    ${table(
      ['Folder', 'Report Count'],
      [...folderCounts.entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([folder, count]) => [escapeHtml(folder), String(count)])
    )}`;
      }
      return '';
    })()}
    ${table(
      ['Report', 'Description'],
      data.appendixB.map((r) => [
        escapeHtml(r.name) + (r.isStale ? ' <strong>⚠ Stale</strong>' : ''),
        escapeHtml(r.description),
      ])
    )}
  </div>`;
}

// ============================================================================
// Appendix C+D: Glossary + Extraction Coverage
// ============================================================================

function renderAppendixCD(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>Appendix C: Glossary</h2>
    ${table(
      ['Term', 'Definition'],
      [
        ['CPQ', 'Configure, Price, Quote — Salesforce quoting application (SBQQ)'],
        ['SBQQ', 'Namespace prefix for CPQ managed package objects'],
        ['sbaa', 'Advanced Approvals managed package'],
        ['QCP', 'Quote Calculator Plugin — JavaScript custom calculation injection'],
      ]
    )}

    <h2>Appendix D: Extraction Coverage</h2>
    ${table(
      ['Category', 'Coverage', 'Notes'],
      data.appendixD.map((d) => [escapeHtml(d.category), badge(d.coverage), escapeHtml(d.notes)])
    )}
  </div>`;
}

// ============================================================================
// Section 6.2: Product Deep Dive [T2 — conditional] (R-04)
// ============================================================================

function renderProductDeepDive(data: ReportData): string {
  const dd = data.productDeepDive;
  if (!dd) return '';

  const summaryBoxes = renderSummaryBoxPair(
    {
      title: 'Product Catalog',
      items: [
        { label: 'Active Products', value: String(dd.summary.activeProducts) },
        { label: 'Inactive Products', value: String(dd.summary.inactiveProducts) },
        { label: 'Bundle-capable Products', value: String(dd.summary.bundleCapableProducts) },
        { label: 'Price Books', value: String(dd.summary.priceBooks) },
      ],
    },
    {
      title: 'Technical Debt Indicators',
      items: [{ label: 'Dormant Products', value: dd.summary.dormantPercent }],
    }
  );

  const pricingTable = table(
    ['Method', 'Count', '% of Active', 'Complexity'],
    dd.pricingMethodDistribution.map((p) => [
      escapeHtml(p.method),
      String(p.count),
      escapeHtml(p.percentOfActive),
      escapeHtml(p.complexity),
    ])
  );

  const subTable = table(
    ['Type', 'Count', '% of Active', 'Notes'],
    dd.subscriptionProfile.map((s) => [
      escapeHtml(s.type),
      String(s.count),
      escapeHtml(s.percentOfActive),
      escapeHtml(s.notes),
    ])
  );

  return `
  <div class="page-break">
    <h2>6.2 Product Deep Dive</h2>
    <p><em>Product Summary (Active Only) — ${dd.summary.activeProducts} Products</em></p>
    ${summaryBoxes}

    ${renderCheckboxTable(
      dd.fieldUtilization,
      '6.2.1 Product Segmentation',
      `% = products with field populated / ${dd.denominatorLabel}`
    )}

    <h4>6.2.2 Pricing Method Distribution</h4>
    ${pricingTable}
    ${renderDenominatorFootnote('products with pricing method', 'active products', dd.summary.activeProducts)}

    <h4>6.2.3 Subscription Profile</h4>
    ${subTable}
    ${renderDenominatorFootnote('products with subscription type', 'active products', dd.summary.activeProducts)}
  </div>`;
}

// ============================================================================
// Section 6.6: Bundles & Options Deep Dive [T2 — conditional] (R-05)
// ============================================================================

function renderBundlesDeepDive(data: ReportData): string {
  const dd = data.bundlesDeepDive;
  if (!dd) return '';

  const summaryBoxes = renderSummaryBoxPair(
    {
      title: 'Bundle Configuration',
      items: [
        { label: 'Bundle-capable', value: String(dd.summary.bundleCapable) },
        { label: 'Configured Bundles', value: String(dd.summary.configuredBundles) },
        { label: 'Nested Bundles', value: String(dd.summary.nestedBundles) },
        { label: 'Avg Options/Bundle', value: dd.summary.avgOptionsPerBundle },
      ],
    },
    {
      title: 'Option Complexity',
      items: [
        { label: 'Total Options', value: String(dd.summary.totalOptions) },
        { label: 'Options w/Constraints', value: dd.summary.optionsWithConstraintsPercent },
        { label: 'Config Attributes', value: dd.summary.configAttributesPercent },
        { label: 'Config Rules', value: dd.summary.configRulesPercent },
      ],
    }
  );

  const bundleFootnote =
    dd.summary.bundleCapable !== dd.summary.configuredBundles
      ? `<p style="font-size:11px;color:#718096;margin-top:4px;"><em>Bundle-capable = products with SBQQ__ConfigurationType__c set (Required or Allowed). Configured Bundles = bundle-capable products that have at least one active SBQQ__ProductOption__c child record. The difference (${dd.summary.bundleCapable - dd.summary.configuredBundles}) reflects bundle-capable products with no options currently attached.</em></p>`
      : '';

  // W2-8 (SI feedback): Nested bundle methodology footnote
  const nestedFootnote =
    dd.summary.nestedBundles > 0
      ? `<p style="font-size:11px;color:#718096;margin-top:4px;"><em>Nested Bundles = SBQQ__ProductOption__c records whose Optional SKU is itself a bundle-capable product. A nested bundle adds a layer of configuration depth — max nesting depth detected across the catalog is reported in the Bundle Configuration summary above.</em></p>`
      : '';

  return `
  <div class="page-break">
    <h2>6.6 Bundles &amp; Options Deep Dive</h2>
    ${summaryBoxes}
    ${bundleFootnote}
    ${nestedFootnote}

    ${renderCheckboxTable(
      dd.relatedObjectUtilization,
      '6.6.1 Related Object Utilization',
      `% = count / ${dd.denominatorLabel}`
    )}
  </div>`;
}

// ============================================================================
// Section 10: Related Functionality Analysis [T2 — conditional] (R-09)
// ============================================================================

function renderRelatedFunctionality(data: ReportData): string {
  const rf = data.relatedFunctionality;
  if (!rf) return '';

  const observationsList =
    rf.observations.length > 0
      ? `<h4>Observations</h4><ul>${rf.observations.map((o) => `<li>${escapeHtml(o)}</li>`).join('')}</ul>`
      : '';

  return `
  <div class="page-break">
    <h2>10. Related Functionality Analysis</h2>
    ${renderBinaryCheckboxTable(rf.items, '10.1 Related Functionality Detection')}
    ${observationsList}
    <p style="font-size:0.85em;color:#666;margin-top:8px;"><em>W2-9 Note: Experience Cloud detection is at the component level (LWC/Aura/VF components). Site-level status (Live vs Down) and site count were not assessed in the current extraction scope. If site-level detail is needed, query the Network object with an admin profile that has "Manage Experiences" permission.</em></p>
  </div>`;
}

// ============================================================================
// Appendix E: Object Configuration Analysis [T2 — conditional] (R-10)
// ============================================================================

function renderAppendixE(data: ReportData): string {
  const configs = data.objectConfiguration;
  if (!configs || configs.length === 0) return '';

  const objectSections = configs
    .map((obj) => {
      const rows = obj.items.map((item) => ({
        label: item.configType,
        used: item.detected,
        notes: item.count > 0 ? `${item.count} — ${item.notes}` : item.notes,
      }));
      return `
      <h4>${escapeHtml(obj.objectName)} Configuration</h4>
      ${renderBinaryCheckboxTable(rows, '')}`;
    })
    .join('');

  return `
  <div class="page-break" id="appendix-e">
    <h2>Appendix E: Object Configuration Analysis</h2>
    <p><em>Metadata-level configuration for CPQ-related objects.</em></p>
    ${objectSections}
  </div>`;
}
