/**
 * Report Template — assembles all sections into a complete HTML document.
 *
 * Each section is a pure function: ReportData → HTML string.
 * CSS is inlined for PDF rendering (no external stylesheets).
 *
 * Updated: Redline mitigation R0–R2 (scoring methodology, tech debt,
 *          feature utilization, expanded scope, active filtering, coverage)
 */

import type { ReportData } from '../assembler.ts';
import { reportStyles } from './styles.ts';
import { escapeHtml, badge, scoreBar, severity, table } from './partials/helpers.ts';

export function renderReport(data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${reportStyles}</style>
</head>
<body>
  ${renderCover(data)}
  ${renderBanners(data)}
  ${renderScope(data)}
  ${renderExecutiveSummary(data)}
  ${renderGlance(data)}
  ${renderSettings(data)}
  ${renderLifecycle(data)}
  ${renderConfigDomain(data)}
  ${renderApprovalsAndDocs(data)}
  ${renderUsage(data)}
  ${renderDataQuality(data)}
  ${renderCustomCode(data)}
  ${renderHotspots(data)}
  ${renderAppendixA(data)}
  ${renderAppendixB(data)}
  ${renderAppendixCD(data)}
</body>
</html>`;
}

// ============================================================================
// Section 1: Cover Page
// ============================================================================

function renderCover(data: ReportData): string {
  const rows: string[][] = [
    ['Client Name', escapeHtml(data.metadata.clientName)],
    ['Salesforce Org ID', escapeHtml(data.metadata.orgId)],
    ['Environment', escapeHtml(data.metadata.environment)],
    ['Assessment Date', escapeHtml(data.metadata.assessmentDate)],
    ['Assessment Period', escapeHtml(data.metadata.assessmentPeriod)],
    ['CPQ Package Version', escapeHtml(data.metadata.cpqVersion)],
  ];
  if (data.metadata.sbaaVersion) {
    rows.push(['Adv. Approvals Version', escapeHtml(data.metadata.sbaaVersion)]);
  }
  rows.push(
    ['Report Generated By', escapeHtml(data.metadata.generatedBy)],
    ['Classification', 'Confidential']
  );

  return `
  <div class="cover">
    <h1>SALESFORCE CPQ<br/>ENVIRONMENT ASSESSMENT REPORT</h1>
    <h2>Current State Configuration & Usage Analysis</h2>
    ${table(['Field', 'Value'], rows)}
    <div class="section-footer">Generated by RevBrain CPQ Assessment Tool</div>
  </div>`;
}

// ============================================================================
// Section 2: Scope & Methodology
// ============================================================================

function renderScope(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>1. Scope & Methodology</h2>
    <p><em>Audience: This report is designed for review of current-state CPQ complexity prior to planning.</em></p>

    <h3>1.1 Assessment Scope</h3>
    <p>This report provides a current-state assessment of the Salesforce CPQ environment. The following areas were assessed:</p>
    <ul>
      <li>CPQ configuration objects (products, bundles, options, constraints, attributes)</li>
      <li>Pricing rules, discount schedules, and custom scripts</li>
      <li>CPQ package settings and plugin configuration</li>
      <li>Quote templates and document generation</li>
      <li>Advanced approval rules and workflows</li>
      <li>90-day transactional usage patterns and trends</li>
      <li>User behavior and adoption metrics</li>
      <li>Discount and override patterns</li>
      <li>Data quality and field completeness</li>
      <li>Technical debt indicators (dormant configs, duplicate rules)</li>
      <li>Custom code: Apex, triggers, flows referencing CPQ objects</li>
      <li>Complexity scoring across 5 weighted dimensions</li>
      <li>Quote lifecycle and integration touchpoints</li>
    </ul>

    <h3>1.2 Methodology</h3>
    <ol>
      <li><strong>Metadata Extraction:</strong> CPQ configuration metadata extracted via Salesforce REST, Tooling, and Metadata APIs.</li>
      <li><strong>Usage & Behavior Analysis:</strong> SOQL queries extract 90-day transactional data including quotes, quote lines, orders, and user activity.</li>
      <li><strong>Data Quality Assessment:</strong> Automated analysis of field completeness, orphaned records, and duplicate detection.</li>
      <li><strong>Custom Code Scan:</strong> Identification of Apex classes, triggers, and flows referencing SBQQ objects via namespace scan.</li>
      <li><strong>Complexity Scoring:</strong> Fixed weighted model (see Section 2.3) normalized against benchmark ranges.</li>
    </ol>

    ${data.metadata.lowVolumeWarning ? `<p><strong>⚠ ${escapeHtml(data.metadata.lowVolumeWarning)}</strong></p>` : ''}

    <h3>1.3 Data Confidence Levels</h3>
    ${table(
      ['Level', 'Label', 'Definition'],
      [
        ['★★★', badge('Confirmed'), 'Directly extracted from Salesforce metadata or SOQL query.'],
        ['★★', badge('Estimated'), 'Derived from available metadata with reasonable inference.'],
        ['★', badge('Partial'), 'Based on incomplete extraction or sampling.'],
        [
          '—',
          badge('Not extracted'),
          'Extraction not attempted or collector did not produce results.',
        ],
      ]
    )}
  </div>`;
}

// ============================================================================
// Section 3: Executive Summary
// ============================================================================

function renderExecutiveSummary(data: ReportData): string {
  const findingsRows = data.executiveSummary.keyFindings.map((f, i) => [
    String(i + 1),
    `<strong>${escapeHtml(f.title)}</strong>`,
    escapeHtml(f.detail),
    badge(f.confidence),
  ]);

  const scores = data.executiveSummary.complexityScores;

  return `
  <div class="page-break">
    <h2>2. Executive Summary</h2>
    <h3>2.1 Key Findings</h3>
    ${table(['#', 'Finding', 'Detail', 'Confidence'], findingsRows)}

    <h3>2.2 Complexity Scores</h3>
    ${scoreBar('Overall Complexity', scores.overall)}
    ${scoreBar('Configuration Depth', scores.configurationDepth)}
    ${scoreBar('Pricing Logic', scores.pricingLogic)}
    ${scoreBar('Customization Level', scores.customizationLevel)}
    ${scoreBar('Data Volume & Usage', scores.dataVolumeUsage)}
    ${scoreBar('Technical Debt', scores.technicalDebt)}
    <p><em>Scores are directional indicators of relative complexity, not absolute measures.</em></p>

    <h3>2.3 Scoring Methodology</h3>
    ${table(
      ['Dimension', 'Weight', 'Score', 'Drivers'],
      data.executiveSummary.scoringMethodology.map((m) => [
        escapeHtml(m.dimension),
        `${m.weight}%`,
        `${m.score}/100`,
        escapeHtml(m.drivers),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 4: CPQ at a Glance
// ============================================================================

function renderGlance(data: ReportData): string {
  const sections = Object.entries(data.cpqAtAGlance);
  const confSummary = data.dataConfidenceSummary;

  return `
  <div class="page-break">
    <h2>3. CPQ at a Glance</h2>
    ${confSummary ? `<p><em>Data confidence summary: approximately ${confSummary.confirmed}% Confirmed, ${confSummary.estimated}% Estimated, ${confSummary.partial}% Partial.</em></p>` : ''}
    <div class="glance-grid">
      ${sections
        .map(
          ([title, metrics]) => `
        <div class="glance-section">
          <h4>${escapeHtml(title)}</h4>
          ${table(
            ['Metric', 'Value', 'Conf.'],
            metrics.map((m) => [
              escapeHtml(m.label),
              `<strong>${escapeHtml(m.value)}</strong>`,
              badge(m.confidence),
            ])
          )}
        </div>
      `
        )
        .join('')}
    </div>
  </div>`;
}

// ============================================================================
// Section 5: Package Settings
// ============================================================================

function renderSettings(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>4. CPQ Package Settings</h2>
    <h3>4.1 Installed Packages</h3>
    ${
      data.packageSettings.installedPackages.length > 0
        ? table(
            ['Package', 'Namespace', 'Version', 'Status'],
            data.packageSettings.installedPackages.map((p) => [
              escapeHtml(p.name),
              escapeHtml(p.namespace),
              escapeHtml(p.version),
              escapeHtml(p.status),
            ])
          )
        : '<p><em>Package inventory available from Discovery collector.</em></p>'
    }

    <h3>4.2 Core CPQ Settings</h3>
    ${table(
      ['Setting', 'Value', 'Notes', 'Confidence'],
      data.packageSettings.coreSettings.map((s) => [
        escapeHtml(s.setting),
        `<strong>${escapeHtml(s.value)}</strong>`,
        escapeHtml(s.notes),
        badge(s.confidence),
      ])
    )}

    <h3>4.3 Plugins</h3>
    ${table(
      ['Plugin', 'Status', 'Notes', 'Confidence'],
      data.packageSettings.plugins.map((p) => [
        escapeHtml(p.plugin),
        `<strong>${escapeHtml(p.status)}</strong>`,
        escapeHtml(p.notes),
        badge(p.confidence),
      ])
    )}
  </div>`;
}

// ============================================================================
// Section 6: Quote Lifecycle
// ============================================================================

function renderLifecycle(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>5. Quote Lifecycle</h2>
    <ol>
      ${data.quoteLifecycle.map((s) => `<li>${escapeHtml(s.description)}</li>`).join('\n')}
    </ol>
  </div>`;
}

// ============================================================================
// Section 7: Configuration Domain
// ============================================================================

function renderConfigDomain(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>6. Configuration Domain Analysis</h2>

    <h3>6.1 Product Catalog</h3>
    ${
      data.configurationDomain.productCatalog.length > 0
        ? table(
            ['Category', 'Active', 'Inactive', 'Quoted 90d', '% Quoted', 'Conf.'],
            data.configurationDomain.productCatalog.map((c) => [
              escapeHtml(c.category),
              String(c.active),
              String(c.inactive),
              String(c.quoted90d),
              escapeHtml(c.percentQuoted),
              badge(c.confidence),
            ])
          )
        : '<p><em>Product catalog breakdown available from Catalog collector.</em></p>'
    }

    <h3>6.2 Price Rules</h3>
    <p><em>${escapeHtml(data.configurationDomain.activePriceRuleSummary)}</em></p>
    ${table(
      ['Rule', 'Description', 'Complexity', 'Status', 'Conf.'],
      data.configurationDomain.priceRules.map((r) => [
        escapeHtml(r.name),
        escapeHtml(r.description),
        severity(r.complexity),
        escapeHtml(r.status),
        badge(r.confidence),
      ])
    )}

    <h3>6.3 Product Rules</h3>
    <p><em>${escapeHtml(data.configurationDomain.activeProductRuleSummary)}</em></p>
    ${table(
      ['Rule', 'Type', 'Description', 'Complexity', 'Status', 'Conf.'],
      data.configurationDomain.productRules.map((r) => [
        escapeHtml(r.name),
        escapeHtml(r.type),
        escapeHtml(r.description),
        severity(r.complexity),
        escapeHtml(r.status),
        badge(r.confidence),
      ])
    )}

    ${
      data.configurationDomain.discountScheduleAnalysis.length > 0
        ? `
    <h3>6.4 Discount Schedules</h3>
    <p><em>${data.configurationDomain.discountScheduleAnalysis.length} unique schedule names (${data.configurationDomain.discountScheduleAnalysis.filter((d) => d.isDuplicate).length} with duplicate names).</em></p>
    ${table(
      ['Schedule Name', 'Status'],
      data.configurationDomain.discountScheduleAnalysis.map((d) => [
        escapeHtml(d.name),
        d.isDuplicate ? '<strong>⚠ Duplicate</strong>' : 'Unique',
      ])
    )}`
        : ''
    }

    ${
      data.configurationDomain.optionAttachmentSummary
        ? `
    <h3>6.5 Product Option Attachment</h3>
    <p>${escapeHtml(data.configurationDomain.optionAttachmentSummary)}</p>`
        : ''
    }
  </div>`;
}

// ============================================================================
// Section 8: Usage & Adoption
// ============================================================================

function renderUsage(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>7. Usage & Adoption Analysis</h2>

    <h3>7.1 90-Day Quoting Activity</h3>
    ${table(
      ['Metric', 'Value', 'Trend', 'Conf.'],
      data.usageAdoption.quotingActivity.map((m) => [
        escapeHtml(m.metric),
        `<strong>${escapeHtml(m.value)}</strong>`,
        escapeHtml(m.trend),
        badge(m.confidence),
      ])
    )}

    <h3>7.2 Conversion by Quote Size</h3>
    ${
      data.usageAdoption.conversionBySize.length > 0
        ? table(
            ['Size', '% Quotes', '% Revenue', 'Conversion', 'Conf.'],
            data.usageAdoption.conversionBySize.map((s) => [
              escapeHtml(s.segment),
              `${s.percentQuotes}%`,
              `${s.percentRevenue}%`,
              `${s.conversionRate}%`,
              badge(s.confidence),
            ])
          )
        : '<p><em>No conversion data available.</em></p>'
    }

    <h3>7.3 Discount Distribution</h3>
    ${
      data.usageAdoption.discountDistribution.length > 0
        ? table(
            ['Range', 'Count', '% Discounted'],
            data.usageAdoption.discountDistribution.map((d) => [
              escapeHtml(d.range),
              String(d.count),
              escapeHtml(d.percent),
            ])
          )
        : '<p><em>No discount data available.</em></p>'
    }

    ${
      data.usageAdoption.overrideAnalysis
        ? `
    <h3>7.4 Manual Price Overrides</h3>
    <p>${data.usageAdoption.overrideAnalysis.count} lines (${data.usageAdoption.overrideAnalysis.rate}%) with manual overrides. Revenue impact: $${data.usageAdoption.overrideAnalysis.revenueImpact.toLocaleString()}.</p>
    `
        : ''
    }

    <h3>7.5 User Behavior by Role</h3>
    ${
      data.usageAdoption.userBehavior.length > 0
        ? table(
            ['Role', 'Users', '% Quotes', 'Conv %'],
            data.usageAdoption.userBehavior.map((u) => [
              escapeHtml(u.profile),
              String(u.users),
              `${u.percentQuotes}%`,
              `${u.conversionRate}%`,
            ])
          )
        : '<p><em>Insufficient user behavior data in assessment window.</em></p>'
    }

    <h3>7.6 Top Quoted Products</h3>
    ${
      data.usageAdoption.topProducts.length > 0
        ? table(
            ['#', 'Product', 'Category', 'Quoted', '% Quotes'],
            data.usageAdoption.topProducts.map((p, i) => [
              String(i + 1),
              escapeHtml(p.name),
              escapeHtml(p.category),
              String(p.quotedCount),
              escapeHtml(p.percentQuotes),
            ])
          )
        : '<p><em>No product quoting data available.</em></p>'
    }
  </div>`;
}

// ============================================================================
// Section 9: Data Quality & Technical Debt
// ============================================================================

function renderDataQuality(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>8. Data Quality & Technical Debt</h2>

    <h3>8.1 Flagged Areas</h3>
    ${
      data.dataQuality.flaggedAreas.length > 0
        ? table(
            ['Issue', 'Status', 'Detail'],
            data.dataQuality.flaggedAreas.map((f) => [
              escapeHtml(f.issue),
              `<strong>${escapeHtml(f.status)}</strong>`,
              escapeHtml(f.detail),
            ])
          )
        : '<p><em>No data quality flags detected.</em></p>'
    }

    <h3>8.2 Technical Debt Inventory</h3>
    ${
      data.dataQuality.technicalDebt.length > 0
        ? table(
            ['Category', 'Count', 'Detail'],
            data.dataQuality.technicalDebt.map((d) => [
              escapeHtml(d.category),
              String(d.count),
              escapeHtml(d.detail),
            ])
          )
        : '<p><em>No technical debt indicators detected.</em></p>'
    }

    <h3>8.3 Feature Utilization</h3>
    ${
      data.dataQuality.featureUtilization.length > 0
        ? table(
            ['Feature', 'Status', 'Detail'],
            data.dataQuality.featureUtilization.map((f) => [
              escapeHtml(f.feature),
              `<strong>${escapeHtml(f.status)}</strong>`,
              escapeHtml(f.detail),
            ])
          )
        : '<p><em>Feature utilization analysis requires collector data.</em></p>'
    }

    <h3>8.4 Field Completeness by Object</h3>
    ${
      data.dataQuality.fieldCompleteness.some((f) => f.totalFields > 0)
        ? table(
            [
              'Object',
              'Total Fields',
              'Fields >50% Populated',
              'Fields <5% Populated',
              'Quality Score',
            ],
            data.dataQuality.fieldCompleteness.map((f) => [
              escapeHtml(f.object),
              String(f.totalFields),
              String(f.above50pct),
              String(f.below5pct),
              escapeHtml(f.score),
            ])
          )
        : table(
            ['Object', 'Status'],
            data.dataQuality.fieldCompleteness.map((f) => [
              escapeHtml(f.object),
              escapeHtml(f.score),
            ])
          )
    }
  </div>`;
}

// ============================================================================
// Section 10: Custom Code & Automation
// ============================================================================

function renderCustomCode(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>9. Custom Code & Automation Inventory</h2>

    <h3>9.1 Apex Classes Referencing SBQQ</h3>
    ${table(
      ['Class Name', 'Lines', 'Purpose', 'Origin'],
      data.customCode.apexClasses.map((a) => [
        escapeHtml(a.name),
        String(a.lines),
        escapeHtml(a.purpose),
        escapeHtml(a.origin),
      ])
    )}

    <h3>9.2 Triggers & Flows</h3>
    ${
      data.customCode.triggersFlows.length > 0
        ? table(
            ['Component', 'Type', 'Object', 'Status'],
            data.customCode.triggersFlows.map((t) => [
              escapeHtml(t.name),
              escapeHtml(t.type),
              escapeHtml(t.object),
              escapeHtml(t.status),
            ])
          )
        : '<p><em>No triggers or flows detected.</em></p>'
    }

    <h3>9.3 Validation Rules</h3>
    ${
      data.customCode.validationRules.length > 0
        ? table(
            ['Object', 'Rule', 'Status', 'Complexity'],
            data.customCode.validationRules.map((v) => [
              escapeHtml(v.object),
              escapeHtml(v.rule),
              escapeHtml(v.status),
              severity(v.complexity),
            ])
          )
        : '<p><em>No validation rules detected.</em></p>'
    }

    ${
      data.customCode.permissionSets.length > 0
        ? `
    <h3>9.4 CPQ Permission Sets</h3>
    ${table(
      ['Permission Set', 'Type', 'Namespace'],
      data.customCode.permissionSets.map((ps) => [
        escapeHtml(ps.name),
        escapeHtml(ps.type),
        escapeHtml(ps.namespace),
      ])
    )}`
        : ''
    }
  </div>`;
}

// ============================================================================
// Validation Banners (V1–V3 warnings, displayed at top of report)
// ============================================================================

function renderBanners(data: ReportData): string {
  if (!data.reportBanners || data.reportBanners.length === 0) return '';
  return `
  <div style="margin: 10px 0; padding: 12px; background: #fff3cd; border: 2px solid #ffc107; border-radius: 6px;">
    ${data.reportBanners.map((b) => `<p style="margin: 4px 0; font-weight: 600; color: #856404;">${escapeHtml(b)}</p>`).join('')}
  </div>`;
}

// ============================================================================
// Section 6.4: Approvals & Document Generation
// ============================================================================

function renderApprovalsAndDocs(data: ReportData): string {
  const { approvalRules, quoteTemplates, documentGeneration } = data.approvalsAndDocs;
  const hasContent = approvalRules.length > 0 || quoteTemplates.length > 0;

  return `
  <div class="page-break">
    <h2>6.4 Approvals & Document Generation</h2>

    <h3>Approval Rules</h3>
    ${
      approvalRules.length > 0
        ? table(
            ['Rule', 'Target Object', 'Conditions', 'Status'],
            approvalRules.map((r) => [
              escapeHtml(r.name),
              escapeHtml(r.object),
              String(r.conditions),
              escapeHtml(r.status),
            ])
          )
        : '<p><em>No approval rules detected. Advanced Approvals (sbaa) may not be installed.</em></p>'
    }

    <h3>Quote Templates</h3>
    ${
      quoteTemplates.length > 0
        ? table(
            ['Template', 'Default', 'Last Modified'],
            quoteTemplates.map((t) => [
              escapeHtml(t.name),
              t.isDefault ? '<strong>Yes</strong>' : 'No',
              escapeHtml(t.lastModified || 'Unknown'),
            ])
          )
        : '<p><em>No quote templates detected.</em></p>'
    }

    <h3>Document Generation</h3>
    <p>${documentGeneration.templateCount} quote template(s) configured. DocuSign integration: <strong>${documentGeneration.docuSignActive ? 'Active' : 'Not detected'}</strong>.</p>
    ${!hasContent ? '<p><em>Approvals and document generation data requires Tier 2 collectors (templates, approvals) to complete successfully.</em></p>' : ''}
  </div>`;
}

// ============================================================================
// Section 11: Complexity Hotspots
// ============================================================================

function renderHotspots(data: ReportData): string {
  if (data.complexityHotspots.length === 0) return '';
  return `
  <div class="page-break">
    <h2>10. Configuration Complexity Hotspots</h2>
    ${table(
      ['Hotspot', 'Severity', 'Analysis'],
      data.complexityHotspots.map((h) => [
        `<strong>${escapeHtml(h.name)}</strong>`,
        severity(h.severity),
        escapeHtml(h.analysis),
      ])
    )}
  </div>`;
}

// ============================================================================
// Appendix A: Object Inventory
// ============================================================================

function renderAppendixA(data: ReportData): string {
  if (data.appendixA.length === 0) return '';

  const cpqObjects = data.appendixA.filter((a) => a.isCpqObject);
  const platformObjects = data.appendixA.filter((a) => !a.isCpqObject);

  const renderTable = (items: typeof data.appendixA) =>
    table(
      ['ID', 'Object(s)', 'API Name', 'Count', 'Complexity', 'Conf.'],
      items.map((a, i) => [
        String(i + 1),
        escapeHtml(a.objectName),
        `<code>${escapeHtml(a.apiName)}</code>`,
        String(a.count),
        severity(a.complexity),
        badge(a.confidence),
      ])
    );

  return `
  <div class="page-break">
    <h2>Appendix A: Configuration Object Inventory</h2>

    <h3>A.1 CPQ Configuration Objects</h3>
    ${cpqObjects.length > 0 ? renderTable(cpqObjects) : '<p><em>No CPQ objects in inventory.</em></p>'}

    ${
      platformObjects.length > 0
        ? `
    <h3>A.2 Platform Metadata Summary</h3>
    ${renderTable(platformObjects)}`
        : ''
    }
  </div>`;
}

// ============================================================================
// Appendix B: Reports & Dashboards
// ============================================================================

function renderAppendixB(data: ReportData): string {
  if (data.appendixB.length === 0) return '';
  return `
  <div class="page-break">
    <h2>Appendix B: CPQ Reports & Dashboards</h2>
    ${table(
      ['Report', 'Description'],
      data.appendixB.map((r) => [escapeHtml(r.name), escapeHtml(r.description)])
    )}
  </div>`;
}

// ============================================================================
// Appendix C+D: Glossary + Extraction Coverage
// ============================================================================

function renderAppendixCD(data: ReportData): string {
  return `
  <div class="page-break">
    <h2>Appendix C: Glossary</h2>
    ${table(
      ['Term', 'Definition'],
      [
        ['CPQ', 'Configure, Price, Quote — Salesforce quoting application (SBQQ)'],
        ['SBQQ', 'Namespace prefix for CPQ managed package objects'],
        ['sbaa', 'Advanced Approvals managed package'],
        ['QCP', 'Quote Calculator Plugin — JavaScript custom calculation injection'],
      ]
    )}

    <h2>Appendix D: Extraction Coverage</h2>
    ${table(
      ['Category', 'Coverage', 'Notes'],
      data.appendixD.map((d) => [escapeHtml(d.category), badge(d.coverage), escapeHtml(d.notes)])
    )}
  </div>`;
}
